# Phase 3's twenty-four goals: the solved cube in each of its orientations.
#
# Phase 3 works with seventeen generators that cannot reach the inner-left
# layer on their own -- measured, 1x2 = x2 . Rw2 . L2, so it needs a whole-cube
# rotation, which is not among its moves. twips has that rotation because its
# phase-3 puzzle is built on Lv and Dv; ours are single layers. Rotating the
# goal supplies what the generators lack: a solution may finish with the cube
# turned, and phase 4 squeezes to a 3x3x3 whose solver does not care.
#
# The set is generated by closing the solved cube under x and y rather than
# written out, so the thing that can be wrong is the two rotation words. They
# are the same hand-written form that got Uw2, Dw2 and Fw2 wrong three times
# over in this file's neighbourhood, so they get the same check: against
# cube_expand_word(), not against the eye.

moves4 <- cube_moves(4)
names(moves4) <- cube_move_names(4)

apply_words <- function(state, words) {
  for (mv in words) state <- state[moves4[[mv]]]
  state
}

# Transcribed from Solver4::init() in src/kociemba4.h.
OUR_ROTATIONS <- list(x = c("L'", "1x", "2x", "R"),
                      y = c("D'", "1y", "2y", "U"))

test_that("the rotation words are the rotations they are named after", {
  for (name in names(OUR_ROTATIONS)) {
    ours <- apply_words(cube_identity(4), OUR_ROTATIONS[[name]])
    theirs <- apply_words(cube_identity(4), cube_expand_word(name, 4))
    expect_identical(ours, theirs, info = name)
  }
})

test_that("each rotation has order four", {
  for (name in names(OUR_ROTATIONS)) {
    word <- OUR_ROTATIONS[[name]]
    state <- cube_identity(4)
    for (i in 1:4) state <- apply_words(state, word)
    expect_identical(state, cube_identity(4), info = name)
  }
})

# The closure is the point: x and y generate the rotation group of the cube,
# which has twenty-four elements. Fewer would mean a rotation word is wrong;
# more is impossible.
test_that("closing the solved cube under x and y gives twenty-four states", {
  seen <- list(cube_identity(4))
  keys <- paste(cube_identity(4), collapse = ",")
  frontier <- list(cube_identity(4))

  while (length(frontier)) {
    nxt <- list()
    for (state in frontier) {
      for (rotation in OUR_ROTATIONS) {
        turned <- apply_words(state, rotation)
        key <- paste(turned, collapse = ",")
        if (!(key %in% keys)) {
          keys <- c(keys, key)
          seen[[length(seen) + 1L]] <- turned
          nxt[[length(nxt) + 1L]] <- turned
        }
      }
    }
    frontier <- nxt
  }

  expect_length(seen, 24L)
})

# Every one of the twenty-four is a solved cube -- turned, but solved. A goal
# that is not solved would be a place phase 3 may stop without having finished.
test_that("all twenty-four orientations are colour-solved and reduced", {
  states <- list(cube_identity(4))
  keys <- paste(cube_identity(4), collapse = ",")
  frontier <- list(cube_identity(4))

  while (length(frontier)) {
    nxt <- list()
    for (state in frontier) {
      for (rotation in OUR_ROTATIONS) {
        turned <- apply_words(state, rotation)
        key <- paste(turned, collapse = ",")
        if (!(key %in% keys)) {
          keys <- c(keys, key)
          states[[length(states) + 1L]] <- turned
          nxt[[length(nxt) + 1L]] <- turned
        }
      }
    }
    frontier <- nxt
  }

  for (i in seq_along(states)) {
    expect_true(cube_is_colour_solved(states[[i]]), info = paste("orientation", i))
    expect_true(cube_is_reduced(states[[i]]), info = paste("orientation", i))
  }
})
