# Phase 3's twenty-four goals: the solved cube in each of its orientations.
#
# Phase 3 works with seventeen generators that cannot reach the inner-left
# layer on their own -- measured, 1x2 = x2 . Rw2 . L2, so it needs a whole-cube
# rotation, which is not among its moves. twips has that rotation because its
# phase-3 puzzle is built on Lv and Dv; ours are single layers. Rotating the
# goal supplies what the generators lack: a solution may finish with the cube
# turned, and phase 4 squeezes to a 3x3x3 whose solver does not care.
#
# The set is generated by closing the solved cube under x and y rather than
# written out, so the thing that can be wrong is the two rotation words. They
# are the same hand-written form that got Uw2, Dw2 and Fw2 wrong three times
# over in this file's neighbourhood, so they get the same check: against
# cube_expand_word(), not against the eye.

moves4 <- cube_moves(4)
names(moves4) <- cube_move_names(4)

apply_words <- function(state, words) {
  for (mv in words) state <- state[moves4[[mv]]]
  state
}

# Transcribed from Solver4::init() in src/kociemba4.h.
OUR_ROTATIONS <- list(x = c("L'", "1x", "2x", "R"),
                      y = c("D'", "1y", "2y", "U"))

test_that("the rotation words are the rotations they are named after", {
  for (name in names(OUR_ROTATIONS)) {
    ours <- apply_words(cube_identity(4), OUR_ROTATIONS[[name]])
    theirs <- apply_words(cube_identity(4), cube_expand_word(name, 4))
    expect_identical(ours, theirs, info = name)
  }
})

test_that("each rotation has order four", {
  for (name in names(OUR_ROTATIONS)) {
    word <- OUR_ROTATIONS[[name]]
    state <- cube_identity(4)
    for (i in 1:4) state <- apply_words(state, word)
    expect_identical(state, cube_identity(4), info = name)
  }
})

# x and y generate the rotation group of the cube, which has twenty-four
# elements. Rather than enumerate them, this checks the presentation that
# forces the count: the rotation group is S4, and <x, y | x^4, y^4, (xy)^3>
# with x and y quarter turns about perpendicular axes is exactly S4. The order
# of x and y is checked above; (xy)^3 is what distinguishes the twenty-four
# from any larger group the words might otherwise generate.
test_that("x and y satisfy the relation that makes them the rotation group", {
  xy <- c(OUR_ROTATIONS$x, OUR_ROTATIONS$y)

  state <- cube_identity(4)
  for (i in 1:3) state <- apply_words(state, xy)
  expect_identical(state, cube_identity(4))

  # and xy is not itself trivial or a half turn -- either would collapse the
  # group to something smaller than twenty-four while (xy)^3 still held.
  expect_false(identical(apply_words(cube_identity(4), xy), cube_identity(4)))
  expect_false(identical(apply_words(apply_words(cube_identity(4), xy), xy),
                         cube_identity(4)))
})

# A rotation leaves the cube solved: turned, but solved. A goal that is not
# solved would be a place phase 3 may stop without having finished. Checking
# the generators covers every product of them, since "solved and reduced" is
# preserved by each.
test_that("the rotations keep the cube colour-solved and reduced", {
  for (name in names(OUR_ROTATIONS)) {
    turned <- apply_words(cube_identity(4), OUR_ROTATIONS[[name]])
    expect_true(cube_is_colour_solved(turned), info = name)
    expect_true(cube_is_reduced(turned), info = name)
  }
})
