#ifndef CAYLEYR_KOCIEMBA_CORE_H
#define CAYLEYR_KOCIEMBA_CORE_H

#include <vector>
#include <string>
#include <map>
#include <cstring>
#include <cstdio>
#include <stdexcept>
#include <stdint.h>
#include <climits>
#include <ctime>
#include <set>

// For the huge-page hint on the prune table, and only for that. Guarded so the
// header still compiles where there is no madvise -- the hint is advisory, and
// a platform without it simply keeps the default pages.
#if defined(__linux__)
#include <sys/mman.h>
#endif

// ---- The machinery a phase solver is built out of -----------------------
//
// Follows twips -- https://github.com/cubing/twips, by Lucas Garron and the
// cubing.js authors, MPL-2.0 -- which is where the shape of all of this comes
// from: the canonical move automaton, the hash prune table grown to half the
// depth about to be searched, the two-level cutoff that abandons a whole move
// class rather than one branch, and the decision to define a search against
// phases rather than against a particular puzzle. Their
// `_internal/search/hash_prune_table.rs` and
// `_internal/search/iterative_deepening/iterative_deepening_search.rs` are the
// files this one answers to.
//
// Everything else in the package searches on stickers, and for a human method
// that is right: a stage predicate reads colours, and a permutation acts on a
// flat vector without needing to know what a corner is. A phase solver cannot
// work that way. "The edges are oriented and the E-slice edges are in the E
// slice" is a statement about pieces and the way round they sit, and no mask
// over 54 stickers says it.
//
// So this file carries a second representation -- orbits of pieces, each with
// a permutation and an orientation -- and three things that operate on it:
//
//   * PieceState / OrbitSpec : the state, and how a move acts on it
//   * CanonicalFSM           : which move may follow which
//   * ida_search             : depth-first iterative deepening, guided by a
//                              hash prune table over a derived coordinate
//
// The three are independent of any particular cube. A phase says what its
// pieces are, what counts as one move, and what it is aiming at; the search
// does not know whether it is reducing a 4x4x4 or finishing a 3x3x3.
//
// ---- What counts as one move --------------------------------------------
//
// Move cost is a property of the phase, not of the package. Kociemba's second
// phase is generated by <U, D, L2, R2, F2, B2>, and a half turn there is one
// move -- not because half turns are cheap but because the group is defined
// that way, and a prune table counting L2 as two steps is a table for a
// different search. Each phase therefore declares its own generator list, and
// depth in the search below is the number of generators used, whatever they
// expand to in quarter turns afterwards.

namespace kociemba {

// ---- Pieces -------------------------------------------------------------
//
// An orbit is a set of pieces that moves among itself: the eight corners of a
// 3x3x3, its twelve edges, the twenty-four wings of a 4x4x4. Each piece has a
// slot it sits in and an orientation, counted modulo however many ways round
// that kind of piece can go -- three for a corner, two for an edge, one for a
// centre, which is to say centres have no orientation at all.

struct OrbitDef {
  std::string name;
  int n_pieces;
  int n_orientations;
};

// A slot number. Orbits are laid end to end and numbered flat across the whole
// state, so this has to hold the total, not the size of one orbit. uint8_t was
// enough while the phases were 3x3x3 and 4x4x4 -- 8 corners, 24 wings, 24
// centres -- but a bigger cube passes 255 slots without any warning that it
// has, and the wrap would be silent and wrong. Orientations stay in uint8_t:
// three is the most any piece has, whatever the puzzle.
typedef uint16_t Slot;

// A state is the orbits laid end to end. perm and ori are parallel, indexed by
// slot: perm[i] is which piece sits in slot i, ori[i] how it is turned.
struct PieceState {
  std::vector<Slot> perm;
  std::vector<uint8_t> ori;

  bool operator==(const PieceState& o) const {
    return perm == o.perm && ori == o.ori;
  }
};

// How one move acts on one orbit: where each piece goes, and how much it is
// twisted on the way. Stored the same way a state is, because a move *is* a
// state -- the one the solved cube becomes after it.
// A run of moves that turn the same face: the outer loop of the search runs
// over these, the inner over the turns within one.
struct MoveClass { int first; int count; };

struct OrbitMove {
  std::vector<Slot> perm;
  std::vector<uint8_t> ori;
};

// The layout of a puzzle for one phase: its orbits, and the moves it may use,
// each already composed to whatever the phase counts as a single step.
struct PuzzleSpec {
  std::vector<OrbitDef> orbits;
  std::vector<int> offset;          // where each orbit starts in the flat state
  int total;                        // total pieces across all orbits
  std::vector<OrbitMove> moves;     // one per move, flat across orbits
  std::vector<std::string> move_names;
  std::vector<int> move_axis;       // for the canonical FSM
  std::vector<int> move_layer;

  int n_moves() const { return (int)moves.size(); }

  // The turns of one face, as a run of consecutive move indices. Generators
  // are declared face by face, so a class is a contiguous slice and needs no
  // storage of its own beyond where it starts and how long it is.
  mutable std::vector<MoveClass> move_classes_;

  const std::vector<MoveClass>& move_classes() const;   // defined below

  // Pieces are numbered flat, across the whole state rather than within each
  // orbit, so that a piece's identity and the slot it belongs in are the same
  // number and solved is simply perm[i] == i. Numbering each orbit from zero
  // would make the second orbit's identities collide with the first's, and a
  // move built from one convention would be read under the other.
  PieceState identity() const {
    PieceState s;
    s.perm.resize(total);
    s.ori.assign(total, 0);
    for (int i = 0; i < total; i++) s.perm[i] = (Slot)i;
    return s;
  }

  void finish_layout() {
    offset.clear();
    total = 0;
    for (size_t o = 0; o < orbits.size(); o++) {
      offset.push_back(total);
      total += orbits[o].n_pieces;
    }
  }

  // Orientation modulus per flat slot, so apply() need not look up the orbit.
  std::vector<uint8_t> ori_mod() const {
    std::vector<uint8_t> m(total, 1);
    for (size_t o = 0; o < orbits.size(); o++) {
      for (int i = 0; i < orbits[o].n_pieces; i++) {
        m[offset[o] + i] = (uint8_t)orbits[o].n_orientations;
      }
    }
    return m;
  }
};

// Apply a move to a state. The piece that ends in slot i is the one that was
// in slot mv.perm[i], and its orientation picks up mv.ori[i] on the way.
inline void apply_move(const PieceState& s, const OrbitMove& mv,
                       const std::vector<uint8_t>& omod, PieceState& out) {
  const size_t n = s.perm.size();
  out.perm.resize(n);
  out.ori.resize(n);
  for (size_t i = 0; i < n; i++) {
    const Slot from = mv.perm[i];
    out.perm[i] = s.perm[from];
    const uint8_t m = omod[i];
    out.ori[i] = m <= 1 ? 0 : (uint8_t)((s.ori[from] + mv.ori[i]) % m);
  }
}

// Compose two moves into one, so a phase can declare "L2" as a generator and
// have it cost a single step.
inline OrbitMove compose(const OrbitMove& a, const OrbitMove& b,
                         const std::vector<uint8_t>& omod) {
  const size_t n = a.perm.size();
  OrbitMove out;
  out.perm.resize(n);
  out.ori.resize(n);
  for (size_t i = 0; i < n; i++) {
    const Slot from = b.perm[i];
    out.perm[i] = a.perm[from];
    const uint8_t m = omod[i];
    out.ori[i] = m <= 1 ? 0 : (uint8_t)((a.ori[from] + b.ori[i]) % m);
  }
  return out;
}

// ---- Which move may follow which ----------------------------------------
//
// A class is the moves that are powers of one another -- U, U2, U' are one
// class, and turning any of them twice running is always reducible. Grouping
// them by equal (axis, layer) says the same thing for a puzzle whose every
// generator turns one layer of one axis, and says the wrong thing as soon as a
// generator is a wide turn, which is how twips writes its 4x4x4 phases. So the
// grouping is measured: two moves share a class when one is a power of the
// other, which is a fact about the permutations and assumes nothing about
// their shape.
//
// Generators are still declared face by face, so a class comes out contiguous
// in practice; the search relies on that and it is asserted below rather than
// hoped for.
inline const std::vector<MoveClass>& PuzzleSpec::move_classes() const {
  if (!move_classes_.empty() || moves.empty()) return move_classes_;

  const int n = (int)moves.size();
  const std::vector<uint8_t> omod = ori_mod();
  const PieceState id = identity();

  // The powers of move m, up to its order: everything m alone can reach.
  // Two moves are in one class when each turns up among the other's powers.
  std::vector<int> class_of(n, -1);
  int n_classes = 0;
  for (int m = 0; m < n; m++) {
    if (class_of[m] >= 0) continue;
    class_of[m] = n_classes;

    // Walk the powers of m and mark every generator met along the way.
    OrbitMove p = moves[m];
    for (int k = 0; k < 8; k++) {          // orders on a cube divide 4; 8 is slack
      bool is_identity = true;
      for (int i = 0; i < (int)p.perm.size(); i++) {
        if (p.perm[i] != id.perm[i] || p.ori[i] != 0) { is_identity = false; break; }
      }
      if (is_identity) break;
      for (int j = 0; j < n; j++) {
        if (class_of[j] >= 0) continue;
        if (p.perm == moves[j].perm && p.ori == moves[j].ori) class_of[j] = n_classes;
      }
      p = compose(moves[m], p, omod);
    }
    n_classes++;
  }

  // Turn the labelling into runs. A class that is not contiguous would break
  // the search's assumption that a class is a slice, so say so loudly rather
  // than search a subset of the moves and call it canonical.
  for (int m = 0; m < n; m++) {
    if (m > 0 && class_of[m] == class_of[m - 1]) {
      move_classes_.back().count++;
    } else {
      for (size_t c = 0; c < move_classes_.size(); c++) {
        const MoveClass& prev = move_classes_[c];
        if (class_of[prev.first] == class_of[m]) {
          throw std::runtime_error("kociemba: move class is not contiguous");
        }
      }
      MoveClass c;
      c.first = m;
      c.count = 1;
      move_classes_.push_back(c);
    }
  }
  return move_classes_;
}

//
// Most words are the same word written differently. "U U'" is nothing, "R L"
// and "L R" are the same because the faces do not touch, and a search that
// explores all of them does the same work many times over. The fix is a small
// automaton that refuses a move when some earlier word reaches the same place.
//
// This follows twips's canonical_fsm.rs rather than keying the state on
// (axis, layer), and the difference matters for anything wider than a single
// layer.
//
// Keying the state on (axis, layer) assumes every move turns one layer of one
// axis. That holds for the package's own alphabet and breaks the moment a
// generator is a wide turn -- one axis, two layers -- which is how twips writes
// its 4x4x4 phases. Registering such a move under one of its layers leaves the
// other unmarked and the automaton refuses continuations that are legal.
//
// So commutation is measured instead of inferred: two move classes commute if
// their permutations compose the same way round, which is a fact about the
// moves and needs no assumption about their shape. A state is the set of
// classes used so far that have not yet been followed by something they do not
// commute with; a class is refused if it is in that set, or if a *later* class
// in the set commutes with it -- which is the rule that picks one order out of
// each commuting group and throws the rest away.
//
// The states are enumerated once at init() and the transitions stored, so the
// search pays only a table lookup.
struct CanonicalFSM {
  // A state is a set of move classes, held as a bitmask: those used so far that
  // nothing since has failed to commute with. States are enumerated at init()
  // and the transitions stored, so the search only ever indexes a table.
  std::vector<uint32_t> commutes_;          // per class, the classes it commutes with
  std::vector<int> class_of_move_;          // move -> class
  std::vector<std::vector<int> > next_;     // state x class -> state, -1 if refused
  int n_classes_;

  // `collapse` is only ever false in the measurement that justifies it being
  // true; the search always takes the default.
  void init(const PuzzleSpec& spec, bool collapse = true) {
    const std::vector<MoveClass>& classes = spec.move_classes();
    n_classes_ = (int)classes.size();
    const std::vector<uint8_t> omod = spec.ori_mod();

    class_of_move_.assign(spec.n_moves(), -1);
    for (int c = 0; c < n_classes_; c++) {
      for (int k = 0; k < classes[c].count; k++) {
        class_of_move_[classes[c].first + k] = c;
      }
    }

    // Whether two classes commute is measured on one representative of each:
    // compose both ways round and compare. Nothing about axes or layers is
    // assumed, which is the whole point -- a wide turn is two layers of one
    // axis and there is no single layer to key it on.
    commutes_.assign(n_classes_, 0);
    for (int i = 0; i < n_classes_; i++) {
      for (int j = 0; j < n_classes_; j++) {
        const OrbitMove& a = spec.moves[classes[i].first];
        const OrbitMove& b = spec.moves[classes[j].first];
        const OrbitMove ab = compose(a, b, omod);
        const OrbitMove ba = compose(b, a, omod);
        if (ab.perm == ba.perm && ab.ori == ba.ori) commutes_[i] |= (1u << j);
      }
    }

    // Enumerate the reachable states, breadth first from the empty set.
    std::map<uint32_t, int> seen;
    std::vector<uint32_t> mask_of;
    seen[0u] = 0;
    mask_of.push_back(0u);
    next_.clear();

    for (size_t q = 0; q < mask_of.size(); q++) {
      const uint32_t mask = mask_of[q];
      next_.push_back(std::vector<int>(n_classes_, -1));

      for (int c = 0; c < n_classes_; c++) {
        // Turning a class already in the set repeats a word already tried:
        // whatever it does, some power of it did the job in one move.
        if (mask & (1u << c)) continue;

        // And of a run of classes that all commute, only one order is kept.
        // A later class sitting in the set means this one should have come
        // first, so the word is a rearrangement of one already seen.
        bool refused = false;
        for (int i = c + 1; i < n_classes_; i++) {
          if ((mask & (1u << i)) && (commutes_[c] & (1u << i))) { refused = true; break; }
        }
        if (refused) continue;

        // What survives: the classes this one commutes with, plus itself.
        // Anything it does not commute with is forgotten -- that is exactly
        // the condition the set is defined by.
        uint32_t nm = (mask & commutes_[c]) | (1u << c);

        // Classes that commute with exactly the same things are
        // interchangeable as far as the refusal rules are concerned, so a
        // state need only remember one of each such group. Without this the
        // number of states grows exponentially in the number of classes, which
        // is what big cubes are: 6 faces plus inner layers, and every parallel
        // layer commutes with the same set. Keep the highest of a group --
        // refusal looks for a *greater* class in the mask, so the highest is
        // the one that rules.
        //
        // Transcribed from twips's canonical_fsm.rs, where the code clears the
        // lower bit; its comment says "clear out the higher ones", which is
        // the opposite. The code is what is followed here.
        if (collapse) {
          for (int i = 0; i < n_classes_; i++) {
            if (!(nm & (1u << i))) continue;
            for (int j = i + 1; j < n_classes_; j++) {
              if ((nm & (1u << j)) && commutes_[i] == commutes_[j]) {
                nm &= ~(1u << i);
                break;
              }
            }
          }
        }

        std::map<uint32_t, int>::iterator it = seen.find(nm);
        int target;
        if (it == seen.end()) {
          target = (int)mask_of.size();
          seen[nm] = target;
          mask_of.push_back(nm);
        } else {
          target = it->second;
        }
        next_[q][c] = target;
      }
    }
  }

  int start() const { return 0; }

  // How many states the construction ended up with, and how many classes it
  // grouped the moves into. Exposed because the collapse above is there to
  // keep the first number from growing exponentially in the second, and that
  // is a claim worth being able to measure rather than assert.
  int n_states() const { return (int)next_.size(); }
  int n_classes() const { return n_classes_; }

  bool allowed(int state, int m) const {
    return next_[state][class_of_move_[m]] >= 0;
  }

  int next(int state, int m) const {
    return next_[state][class_of_move_[m]];
  }
};

// ---- The coordinate a phase searches on ---------------------------------
//
// A phase does not care about the whole cube. Kociemba's first phase cares
// about edge orientation, corner orientation and which edges are in the E
// slice, and nothing else; the pieces it ignores are not merely unimportant,
// they must be ignored, or states that are the same for its purposes look
// different and the search never terminates early.
//
// A PatternDeriver is that projection. It turns a full state into the reduced
// one the phase's prune table and goal test are written against. Masking --
// "forget which piece this is, only that it is some U-layer piece" -- is one
// deriver among others; parity as a coordinate is another, and the reason a
// 4x4x4 phase can refuse to produce a solution that needs a parity fix.

struct Deriver {
  virtual ~Deriver() {}
  virtual void derive(const PieceState& in, PieceState& out) const = 0;
};

// The commonest one: keep the listed slots, blank the rest. A slot given -1 in
// keep_piece keeps its position but loses its identity, which is how "any U
// piece will do" is said.
struct MaskDeriver : public Deriver {
  std::vector<int> keep_perm;   // flat slots whose piece identity matters
  std::vector<int> keep_ori;    // flat slots whose orientation matters
  int total;

  void derive(const PieceState& in, PieceState& out) const {
    out.perm.assign(total, 0);
    out.ori.assign(total, 0);
    for (size_t i = 0; i < keep_perm.size(); i++) {
      const int s = keep_perm[i];
      out.perm[s] = in.perm[s];
    }
    for (size_t i = 0; i < keep_ori.size(); i++) {
      const int s = keep_ori[i];
      out.ori[s] = in.ori[s];
    }
  }
};

// A state as bytes, for hashing and for comparing against a goal.
inline void state_key(const PieceState& s, std::string& out) {
  const size_t n = s.perm.size();
  // A slot is two bytes, an orientation one, so the key is three per slot.
  // Copying perm byte-for-byte would keep half of each slot number and make
  // distinct states collide.
  out.resize(3 * n);
  if (n) {
    std::memcpy(&out[0], &s.perm[0], 2 * n);
    std::memcpy(&out[2 * n], &s.ori[0], n);
  }
}

inline uint64_t state_hash(const PieceState& s) {
  uint64_t h = 1469598103934665603ULL;          // FNV-1a
  for (size_t i = 0; i < s.perm.size(); i++) {
    h ^= s.perm[i]; h *= 1099511628211ULL;
    h ^= s.ori[i];  h *= 1099511628211ULL;
  }
  return h;
}

// ---- The prune table ----------------------------------------------------
//
// A lower bound on how many moves remain, indexed by a hash of the derived
// state. Two states can collide and share an entry; what is stored is the
// smaller depth, which keeps the bound admissible. An underestimate only costs
// time, an overestimate would cost correctness.
//
// Nothing records which states have been visited. That is the part worth
// stating outright, because the obvious implementation -- a set of seen states
// alongside the table -- is what the first version of this file did, and it
// cost a minute and a half to build a table that now takes seconds. It is also
// unnecessary: the table is written depth-first from the goal outwards, each
// entry is only ever written if it is still empty, and a state reached twice
// therefore writes the shallower depth first and the second visit changes
// nothing. The set was tracking information the table already held.
//
// Zero means "not filled in", so depths are stored as 1 + depth. This is not
// only tidiness: a freshly allocated table is already all zeros, so there is
// no initialisation pass at all.

struct PruneTable {
  std::vector<uint8_t> table;
  uint64_t mask;
  uint8_t built_depth;

  // Order follows the declarations below, which is the order the members are
  // actually initialised in; any other order is a -Wreorder warning.
  PruneTable() : mask(0), built_depth(0), min_size(0), max_size(0),
                 loaded(false), n_grows(0),
                 n_writes(0), n_collisions(0), n_visits(0) {}

  size_t min_size, max_size;

  // Set by load_prune_table(), and by nothing else. A table read from a file is
  // as deep as the file says and is not to be deepened: build_phase_tables.R
  // built it, the depth in its name is the depth to search against, and the
  // search's own level loop must not quietly build the next level on top.
  //
  // That it must not is a bug this flag exists to fix rather than a preference.
  // The level loop sizes its fill from the search depth alone -- fill_to =
  // limit/2 -- so a search deep enough eventually asks for one level past the
  // file. extend_prune_table() then walks that level with no node budget (the
  // budget is checked in Searcher::recurse, which this is not) and no interrupt
  // check, so it can neither give up nor be stopped. Measured: with phase 2
  // loaded at depth 5, one cube solved in 6 s and the next hung indefinitely,
  // the difference being only whether its search reached the level that
  // triggers the fill.
  //
  // Cleared wherever the contents stop being the file's: alloc() and grow_to().
  bool loaded;
  // How many times grow_to() has rebuilt this table, over the life of the
  // solver. See grow_to() for why this is the figure to watch rather than the
  // size it ended at.
  long n_grows;

  // What the fill actually managed to record, as opposed to what it walked.
  //
  // These exist because a bound of built_depth + 1 -- the stub -- has two
  // causes that look identical from outside. Either the fill never reached the
  // state, or it reached it and the slot was already taken by a different state
  // that hashed the same way. Only the second is a property of the table rather
  // than of the walk, and telling them apart needs the write path counted, not
  // the read path.
  //
  //   n_writes     slots this fill claimed, i.e. entries the table really holds
  //   n_collisions writes that found the slot taken. First-writer-wins keeps
  //                the bound admissible -- the value kept is the shallower, so
  //                it can only underestimate -- but the arriving state's own
  //                distance is gone, not merely approximated.
  //   n_visits     states the fill derived and offered to the table.
  //
  // n_visits - n_writes is how much of the walk the hash threw away, and
  // n_writes / table.size() is how full the table is. A table near full cannot
  // learn anything from another level however long that level takes to walk.
  long n_writes, n_collisions, n_visits;

  // Ask the kernel for 2MB pages behind a table this size.
  //
  // The table is read once per node and the reads are hash-scattered, so every
  // one of them is a TLB lookup on a different page. At the 4KB default a 256MB
  // table spans 65,536 pages against a TLB holding on the order of 1,500
  // entries, so nearly every read misses and pays a page walk on top of the
  // cache miss it was already paying. Transparent huge pages cover the same
  // table in 128 entries, which the TLB holds outright.
  //
  // Advisory in both directions: the kernel may decline, and where THP is off
  // or madvise is unavailable this compiles to nothing and the table behaves as
  // it always did. Nothing downstream may depend on it having worked.
  //
  // Measured, on a Ryzen 5 5600 with THP in madvise mode and a 256MB table: no
  // change. Phase 3 spent 44.0 s on a 5e7-node candidate against 45.0 s
  // without, which is noise. So the page walks were not what the search was
  // waiting on -- the misses themselves were, and huge pages do not make a
  // miss cheaper. Kept because it costs nothing and the balance differs on
  // other machines and table sizes, but it is not the fix for a table this far
  // past the 32MB L3: only a smaller table is.
  static void advise_huge(void* p, size_t bytes) {
#if defined(__linux__) && defined(MADV_HUGEPAGE)
    if (!p || bytes < (size_t)2 << 20) return;
    const size_t align = (size_t)2 << 20;
    uintptr_t start = ((uintptr_t)p + align - 1) & ~(uintptr_t)(align - 1);
    const uintptr_t end = ((uintptr_t)p + bytes) & ~(uintptr_t)(align - 1);
    if (end > start) madvise((void*)start, (size_t)(end - start), MADV_HUGEPAGE);
#else
    (void)p; (void)bytes;
#endif
  }

  void alloc(size_t size_pow2) {
    size_t sz = 1;
    while (sz < size_pow2) sz <<= 1;
    table.assign(sz, 0);
    advise_huge(table.data(), table.size());
    mask = sz - 1;
    if (min_size == 0) min_size = sz;
    // The counters describe the contents, so they go when the contents go.
    n_writes = n_collisions = n_visits = 0;
    loaded = false;
  }

  // Grow the table to hold roughly `want` entries, within the bounds it was
  // given. Growing throws away what was there -- the hash of a state depends on
  // the table size -- so the depth counter goes back to zero and the levels are
  // refilled, which is cheap next to searching them.
  //
  // A table sized for the level about to be searched is the point: too small
  // and every lookup collides down to a useless bound, too large and the
  // filling costs more than the search it saves.
  bool grow_to(size_t want) {
    size_t sz = 1;
    while (sz < want) sz <<= 1;
    if (sz < min_size) sz = min_size;
    if (max_size && sz > max_size) sz = max_size;
    if (sz <= table.size()) return false;
    table.assign(sz, 0);
    advise_huge(table.data(), table.size());
    mask = sz - 1;
    built_depth = 0;
    n_writes = n_collisions = n_visits = 0;
    // Whatever the file held is gone -- assign() zeroed it -- so the table is
    // the search's own again and may be filled by it.
    loaded = false;
    // Counted because the cost of a growth is the whole table -- assign() zeroes
    // every slot, and the levels already filled are discarded and have to be
    // walked again. A phase that grows repeatedly pays that each time, and the
    // final size alone does not show it happened.
    n_grows++;
    return true;
  }

  // A state the table never reached is at least one move further than the
  // deepest level built -- that is the whole content of "the search got this
  // far and did not find it". Returning built_depth instead would claim a
  // state beyond the frontier is *at* the frontier, which is an overestimate
  // and would let the search prune away real solutions.
  uint8_t get(uint64_t h) const {
    const uint8_t v = table[h & mask];
    return v == 0 ? (uint8_t)(built_depth + 1) : (uint8_t)(v - 1);
  }

  // First writer wins. The table is filled shallowest-first, so the first
  // value written to a slot is the smallest, and a later deeper visit must not
  // overwrite it.
  //
  // n_collisions counts arrivals at a taken slot without claiming to know
  // whether the state already there is this one or a different one that hashed
  // alike -- a byte of depth cannot say. It is an upper bound on the entries
  // the hash cost us, and the fill revisits states often enough that it will
  // exceed the true figure. What makes it worth having is the pair it forms
  // with n_writes: writes are the table's real content, and when writes stop
  // rising while visits keep rising, the table is full and deeper levels are
  // being walked for nothing.
  void set_if_empty(uint64_t h, uint8_t d) {
    n_visits++;
    uint8_t& slot = table[h & mask];
    if (slot == 0) {
      slot = (uint8_t)(d + 1);
      n_writes++;
    } else {
      n_collisions++;
    }
  }
};

// The table is filled depth first, one target depth at a time, so that every
// entry is written at the shallowest depth it can be reached at. Moves are
// applied forwards from the goal, which reaches the same states as searching
// backwards would because a phase's generators are closed under inverse.
//
// The recursion carries *full* states, because only a full state can have a
// move applied to it: a derived state is a summary, not a member of the group,
// and feeding one back into apply_move would read its blanked-out entries as
// though they were pieces. What gets written into the table is the *derived*
// state, so two full states the phase cannot tell apart share one entry.
//
// The canonical FSM is applied here as well as in the search. Without it the
// recursion re-walks the same words in different orders and the build time
// grows by an order of magnitude for no extra coverage.
inline void fill_prune_table(const PuzzleSpec& spec, const Deriver& deriver,
                             const CanonicalFSM& fsm,
                             const std::vector<uint8_t>& omod,
                             const PieceState& s, int fsm_state,
                             int remaining, int depth, PruneTable& out) {
  PieceState d;
  deriver.derive(s, d);
  out.set_if_empty(state_hash(d), (uint8_t)depth);
  if (remaining == 0) return;

  PieceState next;
  for (int m = 0; m < spec.n_moves(); m++) {
    if (!fsm.allowed(fsm_state, m)) continue;
    apply_move(s, spec.moves[m], omod, next);
    // A move that changes nothing is a move that need not be followed: it
    // cannot lead anywhere the state it came from does not already reach.
    if (next == s) continue;
    fill_prune_table(spec, deriver, fsm, omod, next, fsm.next(fsm_state, m),
                     remaining - 1, depth + 1, out);
  }
}

// ---- The same table, filled breadth first ---------------------------------
//
// fill_prune_table above walks WORDS; this walks STATES. The difference is not
// a refinement, it is the whole cost of building the table.
//
// The depth-first fill enumerates every allowed word up to the target length
// and writes at each node. The canonical FSM removes the reorderings of
// commuting moves, but nothing removes two genuinely different words that
// arrive at the same state -- and on this coordinate almost every word does.
// Measured on phase 3 to depth 6: 150,089,448 visits produced 8,310,614
// writes, so ninety-four per cent of the walk landed on states already
// recorded, while the table itself sat at three per cent full. That is not the
// hash colliding; it is the same states being reached again and again.
//
// Breadth first visits each state once. It keeps a frontier, expands it a
// level at a time, and adds a successor only if the table has no entry for it
// yet -- so the table doubles as the visited set and no separate one is
// needed. The cost falls from "words of length d" to "states within d", which
// on phase 3's level 6 is 1.5 million rather than 150 million.
//
// What it costs instead is memory. The frontier holds full PieceStates,
// because only a full state can have a move applied to it, and phase 3's
// levels grow by about twelve per level: level 6 is around 1.5 million states,
// level 7 around 18 million. A frontier of 18 million full states is several
// gigabytes, so `max_frontier` caps it -- on hitting the cap the fill stops
// after the current level rather than allocating without bound, and reports
// the depth it reached. The caller can then decide whether to accept a
// shallower table or raise the cap.
//
// The `first writer wins` rule is preserved for the same reason it exists in
// the depth-first version: levels are filled in order, so the first value
// written for a state is the shallowest, and the bound stays admissible.
//
// Unlike extend_prune_table this is not additive across calls. It always
// starts from the goals, and on a table already filled to depth d every state
// it meets in the first d levels is occupied, so the frontier empties at once
// and it returns having done nothing. Deepening an existing table means
// filling it again from scratch with the larger depth, which is cheap enough
// breadth first that the additive machinery is not worth reproducing.
//
// One caveat on the visited test. Two states the hash sends to one slot are
// indistinguishable here, so the second is treated as already seen and its
// successors are never expanded. That can leave states unreached that a
// collision-free run would have found -- the table stays admissible, since
// every entry it holds is still a true shallowest depth, but coverage is a
// little lower than the level sizes suggest. At three per cent occupancy this
// is rare; at eighty per cent it would not be.
//
// Two sets, not one, and that is the correction rather than an economy.
//
// The table used to serve as the visited set as well, and phase 2 is where
// that showed. A successor whose coordinate was already written got dropped
// from the frontier -- but a coordinate is written once while many full states
// carry it, and every one of them after the first was discarded along with
// everything reachable through it. Phase 2's deriver keeps only the centre axes
// and a parity bit, so the collapse was total rather than occasional: the
// frontier emptied at depth 1, the loop read that as "the coordinate is
// exhausted", and the table was saved holding 12 entries against the 116,538 a
// depth-first fill of the same table reaches. A table of 12 entries bounds
// nothing -- a miss scores built_depth + 1 = 2 -- and phase 2 spent 42 seconds
// of a 55 second solve searching without a heuristic.
//
// Expanding the coordinate itself instead of the state would be cheaper still,
// and does not work here: it needs derive(apply_move(s, m)) to equal
// apply_move(derive(s), m), and that identity fails on all three phases when
// measured -- 1438 of 1440 random pairs disagree on phase 3. The derived state
// is not a state these moves act on. So the walk stays on full states, and the
// visited set has to be its own.
//
// What it costs: seen_states holds every full state reached, which is memory
// proportional to the walk rather than to the table. max_frontier bounds the
// level; this is unbounded across levels, and deep fills on a large phase will
// feel it.
inline int fill_prune_table_bfs(const PuzzleSpec& spec, const Deriver& deriver,
                                const std::vector<PieceState>& goals,
                                int new_depth, PruneTable& out,
                                size_t max_frontier = (size_t)40e6) {
  const std::vector<uint8_t> omod = spec.ori_mod();

  std::vector<PieceState> frontier, next;
  PieceState d;

  // Visited full states, kept apart from the table. The table records
  // coordinates and cannot serve as the visited set: many full states share a
  // coordinate, and treating the second one as seen is what stopped phase 2 at
  // depth 1. This set is what keeps the walk finite instead.
  std::set<std::string> seen_states;
  std::string sk;

  // Depth zero: the goals themselves.
  for (size_t i = 0; i < goals.size(); i++) {
    deriver.derive(goals[i], d);
    const uint64_t h = state_hash(d);
    out.set_if_empty(h, 0);
    state_key(goals[i], sk);
    if (seen_states.insert(sk).second) frontier.push_back(goals[i]);
  }
  if ((int)out.built_depth < 0) out.built_depth = 0;

  int reached = 0;
  PieceState nxt;

  for (int depth = 1; depth <= new_depth; depth++) {
    next.clear();

    for (size_t f = 0; f < frontier.size(); f++) {
      for (int m = 0; m < spec.n_moves(); m++) {
        apply_move(frontier[f], spec.moves[m], omod, nxt);
        if (nxt == frontier[f]) continue;

        // Seen this full state before? Then everything through it has been
        // walked already. This is the only test that may stop an expansion.
        state_key(nxt, sk);
        if (!seen_states.insert(sk).second) continue;

        deriver.derive(nxt, d);
        const uint64_t h = state_hash(d);
        // An occupied slot means this coordinate already has a depth no
        // greater than this one, so there is nothing to write -- but the state
        // is still expanded, because its successors may hold coordinates that
        // nothing else reaches.
        if (out.table[h & out.mask] != 0) { out.n_visits++; out.n_collisions++; }
        else out.set_if_empty(h, (uint8_t)depth);
        next.push_back(nxt);
      }
    }

    frontier.swap(next);
    out.built_depth = (uint8_t)depth;
    reached = depth;

    // Nothing new at this depth means the coordinate is exhausted; deeper
    // levels would find nothing either.
    if (frontier.empty()) break;

    // Stop before allocating a frontier larger than the caller allowed. The
    // level just finished is complete and written, so the table is usable as
    // it stands.
    if (frontier.size() > max_frontier) break;
  }

  return reached;
}

// ---- Keeping a filled table between processes ------------------------------
//
// A table is a byte per slot and nothing else, so writing it out is fwrite of
// the vector. What needs care is reading one back: a table whose contents no
// longer match the phase that will consult it does not crash, it returns wrong
// bounds, and wrong bounds prune away branches that hold solutions. The search
// then reports "no solution" on a cube that has one, which looks like a bug
// anywhere except where it is.
//
// The header exists to make that impossible. It records what the contents
// depend on -- the table size, because the hash is `h & mask`; the depth it was
// filled to; how many entries it holds; and a signature of the generators and
// goals the fill walked. Any of those differing means the file describes a
// different table, and load refuses it rather than guessing. The generator set
// in particular has been wrong in this package before -- the wide half turns
// once had layer 1 where layer 2 belongs -- and a stale file would reintroduce
// exactly that with no symptom at the call site.
struct PruneTableHeader {
  char     magic[8];      // "CAYLEYP3"
  uint32_t version;
  uint64_t size;          // slots, always a power of two
  uint32_t built_depth;
  uint64_t n_writes;
  uint64_t signature;     // generators and goals the fill was built from
};

// A cheap order-sensitive hash over the move names and the goal states. Not
// cryptographic and does not need to be: it is guarding against a rebuilt
// package or an edited generator list, not against a forged file.
inline uint64_t prune_signature(const PuzzleSpec& spec,
                                const std::vector<PieceState>& goals) {
  uint64_t h = 1469598103934665603ULL;          // FNV-1a offset basis
  const uint64_t prime = 1099511628211ULL;
  for (size_t m = 0; m < spec.move_names.size(); m++) {
    const std::string& nm = spec.move_names[m];
    for (size_t c = 0; c < nm.size(); c++) { h ^= (uint8_t)nm[c]; h *= prime; }
    h ^= 0xff; h *= prime;
  }
  for (size_t i = 0; i < goals.size(); i++) {
    const PieceState& s = goals[i];
    for (size_t k = 0; k < s.perm.size(); k++) { h ^= (uint8_t)s.perm[k]; h *= prime; }
    for (size_t k = 0; k < s.ori.size(); k++)  { h ^= (uint8_t)s.ori[k];  h *= prime; }
  }
  return h;
}

// Returns true on success. A partial write leaves a file that load will refuse
// on its entry count, so a failure here cannot quietly produce a usable-looking
// table.
inline bool save_prune_table(const std::string& path, const PruneTable& t,
                             uint64_t signature) {
  FILE* f = fopen(path.c_str(), "wb");
  if (!f) return false;

  PruneTableHeader h;
  std::memset(&h, 0, sizeof(h));
  std::memcpy(h.magic, "CAYLEYP3", 8);
  h.version     = 1;
  h.size        = (uint64_t)t.table.size();
  h.built_depth = (uint32_t)t.built_depth;
  h.n_writes    = (uint64_t)t.n_writes;
  h.signature   = signature;

  bool ok = fwrite(&h, sizeof(h), 1, f) == 1;
  if (ok && !t.table.empty()) {
    ok = fwrite(t.table.data(), 1, t.table.size(), f) == t.table.size();
  }
  fclose(f);
  return ok;
}

// Reasons a load can fail, so the caller can say which rather than "no".
enum PruneLoadResult {
  PRUNE_LOAD_OK = 0,
  PRUNE_LOAD_NO_FILE,
  PRUNE_LOAD_BAD_MAGIC,
  PRUNE_LOAD_BAD_VERSION,
  PRUNE_LOAD_BAD_SIGNATURE,   // different generators or goals
  PRUNE_LOAD_SHORT_READ
};

inline PruneLoadResult load_prune_table(const std::string& path, PruneTable& t,
                                        uint64_t signature) {
  FILE* f = fopen(path.c_str(), "rb");
  if (!f) return PRUNE_LOAD_NO_FILE;

  PruneTableHeader h;
  if (fread(&h, sizeof(h), 1, f) != 1) { fclose(f); return PRUNE_LOAD_SHORT_READ; }
  if (std::memcmp(h.magic, "CAYLEYP3", 8) != 0) {
    fclose(f); return PRUNE_LOAD_BAD_MAGIC;
  }
  if (h.version != 1) { fclose(f); return PRUNE_LOAD_BAD_VERSION; }
  if (h.signature != signature) { fclose(f); return PRUNE_LOAD_BAD_SIGNATURE; }
  if (h.size == 0 || (h.size & (h.size - 1)) != 0) {
    fclose(f); return PRUNE_LOAD_SHORT_READ;
  }

  std::vector<uint8_t> buf((size_t)h.size);
  const size_t got = fread(buf.data(), 1, buf.size(), f);
  fclose(f);
  if (got != buf.size()) return PRUNE_LOAD_SHORT_READ;

  t.table.swap(buf);
  t.mask = (uint64_t)h.size - 1;
  t.built_depth = (uint8_t)h.built_depth;
  t.n_writes = (long)h.n_writes;
  t.n_visits = (long)h.n_writes;
  t.n_collisions = 0;
  // The loaded size is also the floor and ceiling from here on. Without this a
  // search could call grow_to(), which reallocates and discards -- and the
  // whole point of loading was not to build it again.
  t.min_size = (size_t)h.size;
  t.max_size = (size_t)h.size;
  // And this is the file's table now: final at the depth it was built to. See
  // PruneTable::loaded for what the search would otherwise do to it.
  t.loaded = true;
  return PRUNE_LOAD_OK;
}

// Extend the table to `new_depth`, filling in only the levels it does not
// already have. Levels already built are not rebuilt: the entries they hold
// are the shallowest reachable, and re-walking them would find nothing new.
//
// Each round fills in everything at exactly one depth. Going straight to the
// target in a single pass would reach some states by a long word before a
// short one and, with first-writer-wins, record them too deep -- an
// overestimate, which is the one error the table must not make.
inline void extend_prune_table(const PuzzleSpec& spec, const Deriver& deriver,
                               const std::vector<PieceState>& goals,
                               int new_depth, PruneTable& out) {
  if (new_depth <= (int)out.built_depth) return;

  CanonicalFSM fsm;
  fsm.init(spec);
  const std::vector<uint8_t> omod = spec.ori_mod();

  for (int depth = (int)out.built_depth + 1; depth <= new_depth; depth++) {
    for (size_t i = 0; i < goals.size(); i++) {
      fill_prune_table(spec, deriver, fsm, omod, goals[i], fsm.start(),
                       depth, 0, out);
    }
    out.built_depth = (uint8_t)depth;
  }
}

inline void build_prune_table(const PuzzleSpec& spec, const Deriver& deriver,
                              const std::vector<PieceState>& goals,
                              size_t table_size, int max_depth,
                              PruneTable& out) {
  out.alloc(table_size);
  // Depth 0 -- the goals themselves -- is what makes an empty table usable at
  // all, and the rest is filled in as the search asks for it.
  for (size_t i = 0; i < goals.size(); i++) {
    PieceState d;
    deriver.derive(goals[i], d);
    out.set_if_empty(state_hash(d), 0);
  }
  out.built_depth = 0;
  if (max_depth > 0) extend_prune_table(spec, deriver, goals, max_depth, out);
}

// ---- The search ---------------------------------------------------------
//
// Iterative deepening with the table as heuristic. The bound rises by one each
// round; within a round the recursion refuses any branch whose table entry
// says it cannot finish in what is left, and the FSM refuses any move that
// would repeat a word already tried.

struct SearchLimits {
  int max_depth;
  long node_budget;
  // How often to report progress, in nodes; 0 for silence, which is the
  // default and what every caller but the benchmark wants. A long phase is
  // otherwise indistinguishable from a hung one -- fifty million nodes is the
  // best part of a minute with nothing on the screen.
  long progress_every;
  // Levels to build the prune table beyond the usual half of the search depth.
  // Zero is the normal rule; raising it trades table-building time for a
  // sharper heuristic, and the point of having it as a dial is to find out
  // what that trade is actually worth on phase 3.
  int prune_depth_bonus;
  SearchLimits()
    : max_depth(30), node_budget(200000000L), progress_every(0),
      prune_depth_bonus(0) {}
};

// Where progress goes. A function pointer rather than a stream, because this
// header knows nothing of R and Rcpp::Rcout is the only thing that prints
// safely from inside a package.
typedef void (*ProgressFn)(int depth_limit, long nodes);

// What one round of iterative deepening cost, kept per level.
//
// A phase reports one number -- seconds, nodes -- and that number is a sum over
// levels whose sizes differ by the branching factor, so it says nothing about
// where the time went. The levels are what the search actually does, and only
// the per-level split can tell "the heuristic stopped pruning at depth 13" from
// "the whole phase is uniformly slow", which are different problems with
// different fixes.
//
//   fill_secs   building the prune table for this level, before the search
//   fill_to     the depth it was filled to (limit/2 + bonus, see the loop)
//   search_secs the recursion itself
//   nodes       nodes visited in this level alone, not the running total
//
// Rates are left to the caller: nodes / search_secs is division, and a struct
// that stores a derived number invites the two to disagree.
struct DepthStat {
  int limit;
  int fill_to;
  long nodes;
  double fill_secs;
  double search_secs;
  DepthStat() : limit(0), fill_to(-1), nodes(0), fill_secs(0.0),
                search_secs(0.0) {}
};

// Seconds, the same way kociemba4.h measures the phases -- so a per-level sum
// and the phase total it belongs to are the same kind of number and can be
// subtracted from one another without a unit mismatch hiding in the difference.
inline double kc_now() {
  return (double)clock() / (double)CLOCKS_PER_SEC;
}

// Called as each level of iterative deepening finishes, with what it cost.
// Separate from ProgressFn: that one fires mid-level on a node count and says
// how far along the search is, this one fires once per level and says what the
// level was worth. A caller that wants a running display wants the first; a
// caller profiling where the phase went wants the second.
typedef void (*DepthDoneFn)(const DepthStat& stat);

// A phase may refuse a solution that reaches its goal. Reaching the goal is
// not always enough: a phase can leave the cube in a position the phase after
// it cannot finish from, and the cheapest place to rule that out is here, by
// rejecting the solution and letting the search carry on to the next one.
struct SolutionFilter {
  virtual ~SolutionFilter() {}
  virtual bool accept(const PieceState& final_state) const = 0;

  // The same test, told which moves reached the state. A filter that only
  // judges the position ignores this and needs no code -- the default forwards
  // to accept() -- while one that collects solutions to hand back needs the
  // word, because a phase-2 state cannot be turned back into stickers:
  // from_stickers4() reads centres by colour, so the conversion is one-way and
  // only the moves can carry a solution across to the caller.
  virtual bool accept_word(const PieceState& final_state,
                           const std::vector<int>& /*word*/) const {
    return accept(final_state);
  }
};

// How much work the prune table did, as opposed to how big it is.
//
// A table can be built, sized, filled and consulted on every node and still
// prune nothing, if the bounds it returns never exceed the depth remaining.
// That is not a worse heuristic than a good one -- it is no heuristic at all,
// and the node count cannot tell the two apart. Measured on phase 3: filling
// from depth 4 to depth 6 left the count at exactly 200,001 on four different
// cubes, unchanged to the last digit.
//
//   cuts / lookups  the share of nodes where the bound exceeded what remained
//   mean_bound      what the table says on average, against the depths being
//                   searched -- a mean far below the remaining depth is a
//                   table that cannot prune whatever its size
struct PruneStats {
  long lookups, cuts, class_cuts;
  double mean_bound;
  PruneStats() : lookups(0), cuts(0), class_cuts(0), mean_bound(0.0) {}
};


// A second opinion on how far a state still has to go.
//
// The hash table above is one lower bound and an exact table over a smaller
// coordinate is another; the search may use both, and takes the larger. Larger
// is the only combination available: each is a lower bound on the same
// quantity, so the greater of the two is still a lower bound, while their sum
// is not -- one move can reduce both at once, and a bound that overestimates
// prunes away the solution instead of merely working slowly.
//
// Declared here as an interface so that this file, which knows nothing about
// any particular puzzle, does not have to learn what a centre is. The 4x4x4's
// implementation lives in centre_table.h.
struct ExtraBound {
  virtual ~ExtraBound() {}
  virtual uint8_t bound(const PieceState& derived) const = 0;
};

struct Searcher {
  const PuzzleSpec* spec;
  const Deriver* deriver;
  const PruneTable* prune;
  const ExtraBound* extra;              // may be null
  const SolutionFilter* filter;         // may be null
  std::vector<std::string> goal_keys;   // derived goals, as byte strings
  CanonicalFSM fsm;
  std::vector<uint8_t> omod;
  long nodes;

  bool is_goal(const PieceState& derived) const {
    std::string k; state_key(derived, k);
    for (size_t i = 0; i < goal_keys.size(); i++) {
      if (goal_keys[i] == k) return true;
    }
    return false;
  }

  long budget;
  bool exhausted;        // the budget ran out before the level was finished
  bool skip_move_class;  // the child's bound was hopeless by more than one

  // Whether the heuristic is doing anything, counted rather than inferred.
  // prune_cuts / prune_lookups is the share of nodes the table actually
  // pruned; a table that is filled and consulted but never crosses the
  // threshold reads as zero here while looking healthy everywhere else.
  long prune_lookups, prune_cuts, prune_class_cuts;
  double prune_bound_sum;

  // The branch that came closest, kept so a failed search can still say where
  // it was trying to go. "Closest" is the smallest bound the prune table gave
  // any node visited -- the table's own estimate of how far that state still
  // had to travel -- with ties broken towards the shallower branch, since two
  // states the table cannot tell apart are better reported by the one reached
  // in fewer moves.
  //
  // This is a diagnostic, not a result. A search that fails has not found a
  // path to anywhere, and the bound is an estimate from a table that collides;
  // the branch below is where the search spent its effort, which is a
  // different claim from the branch being close to solved.
  //
  // The copy happens only when the record improves, so the cost is a compare
  // per node rather than a copy per node.
  int best_bound;
  std::vector<int> best_word;

  long progress_every;   // 0 = say nothing
  long next_progress;
  ProgressFn progress;
  int current_limit;     // the depth this round is searching to, for the report

  bool recurse(const PieceState& s, int depth, int limit, int fsm_state,
               std::vector<int>& word) {
    // The budget has to be tested here rather than between rounds. A single
    // round of phase 2 is ten generators to depth eighteen, and a check that
    // only happens once the round is over is a check that never happens: the
    // search looks like a hang, which is exactly how this was first noticed.
    if (++nodes > budget) { exhausted = true; return false; }

    // Same reasoning, same place: progress that only prints between rounds
    // prints nothing during the round that is taking all the time. Guarded by
    // a counter comparison, so silence costs one predictable branch per node.
    if (progress_every && nodes >= next_progress) {
      next_progress = nodes + progress_every;
      if (progress) progress(current_limit, nodes);
    }

    PieceState d;
    deriver->derive(s, d);
    if (depth == limit) {
      if (!is_goal(d)) return false;
      // The goal is reached; the phase may still refuse this particular way of
      // reaching it, in which case the search keeps looking.
      return filter == 0 || filter->accept_word(s, word);
    }

    // How far the table says there is left to go, against how far there is
    // left to look. Two thresholds rather than one, which is the part that is
    // easy to write as a single test and lose most of the pruning to.
    //
    // If the bound merely exceeds what remains, this branch is dead. If it
    // exceeds it by more than one, then no single move can rescue it either --
    // one move changes the bound by at most one -- so every sibling reachable
    // by turning the same face again is dead with it, and the caller is told
    // to drop the whole move class instead of trying each in turn.
    const int remaining = limit - depth;
    int bound = (int)prune->get(state_hash(d));

    // The exact table's opinion, when there is one. Maximum, never sum: see
    // ExtraBound. A miss returns 0 and changes nothing.
    if (extra) {
      const int b2 = (int)extra->bound(d);
      if (b2 > bound) bound = b2;
    }

    // Counted because node totals cannot tell "the heuristic got better" from
    // "the heuristic is not firing at all", and the difference decides what to
    // work on. Filling the table from depth 4 to 6 left the node count
    // identical to the digit -- 200,001 at every depth, on four different
    // cubes -- which is what a bound that never crosses the threshold looks
    // like, and nothing like a bound that prunes a little less well.
    prune_lookups++;
    prune_bound_sum += bound;
    if (bound > remaining) prune_cuts++;
    if (bound > remaining + 1) prune_class_cuts++;

    // Recorded before the two cuts below, so the branch that came closest is
    // kept even when it is one the search then abandons -- which is the usual
    // case, and the one worth reporting.
    //
    // Strictly less than, with no tie-break on length. An earlier version
    // preferred the shorter branch on a tie, which reported a branch that had
    // never been anywhere: the record is set at depth 0 by the start state
    // itself, and every later node holding the same bound with a shorter path
    // overwrote it. What came back was six moves that changed no measure at
    // all, next to a reported bound of zero -- two claims that cannot both be
    // true, which is how the bug was caught.
    if (bound < best_bound) {
      best_bound = bound;
      best_word = word;
    }

    if (bound > remaining + 1) { skip_move_class = true; return false; }
    if (bound > remaining) return false;

    // Two nested loops, not one: the outer runs over move classes -- the faces
    // -- and the inner over the turns of that one face. The distinction is
    // what makes the "hopeless by more than one" case usable, because what it
    // licenses is abandoning the rest of the current face while carrying on
    // with the next one. A single flat loop has nowhere to put that.
    PieceState next;
    const std::vector<MoveClass>& classes = spec->move_classes();
    for (size_t ci = 0; ci < classes.size(); ci++) {
      const MoveClass& cls = classes[ci];
      for (int k = 0; k < cls.count; k++) {
        const int m = cls.first + k;
        if (!fsm.allowed(fsm_state, m)) continue;
        apply_move(s, spec->moves[m], omod, next);
        if (next == s) continue;

        word.push_back(m);
        skip_move_class = false;
        // The move stays on the word when the branch succeeds -- the word is
        // the solution being built, not a scratch stack, so popping before the
        // result is known returns a solution with its moves removed.
        if (recurse(next, depth + 1, limit, fsm.next(fsm_state, m), word)) {
          return true;
        }
        word.pop_back();

        if (exhausted) return false;
        if (skip_move_class) { skip_move_class = false; break; }
      }
    }
    return false;
  }
};

// What a search did, as opposed to what it returned. "No solution" and "I ran
// out of budget" are different facts and a caller that cannot tell them apart
// will go looking for a bug in the algorithm when the answer is to raise a
// limit -- which is time this file has already cost once.
enum SearchOutcome { SEARCH_FOUND, SEARCH_NO_SOLUTION, SEARCH_EXHAUSTED };

// Search for a word taking `start` to any goal. `word` holds the solution when
// the outcome is SEARCH_FOUND; `nodes_used`, when given, reports how much of
// the budget went on it.
inline SearchOutcome ida_search_outcome(const PuzzleSpec& spec,
                                        const Deriver& deriver,
                                        const PruneTable& prune,
                                        const std::vector<PieceState>& goals,
                                        const PieceState& start,
                                        const SearchLimits& limits,
                                        std::vector<int>& word,
                                        long* nodes_used = 0,
                                        PruneTable* mutable_prune = 0,
                                        const SolutionFilter* filter = 0,
                                        ProgressFn progress = 0,
                                        PruneStats* prune_stats = 0,
                                        std::vector<int>* best_word = 0,
                                        int* best_bound = 0,
                                        const ExtraBound* extra = 0,
                                        std::vector<DepthStat>* depth_stats = 0,
                                        DepthDoneFn depth_done = 0) {
  Searcher S;
  S.spec = &spec;
  S.deriver = &deriver;
  S.prune = &prune;
  S.extra = extra;
  S.filter = filter;
  S.omod = spec.ori_mod();
  S.nodes = 0;
  S.budget = limits.node_budget;
  S.exhausted = false;
  S.prune_lookups = S.prune_cuts = S.prune_class_cuts = 0;
  S.prune_bound_sum = 0.0;
  // Set once, outside the deepening loop: the closest branch is the closest
  // over the whole search, and resetting per level would report only what the
  // last and shallowest-pruned level happened to see.
  S.best_bound = INT_MAX;
  S.best_word.clear();
  S.skip_move_class = false;
  S.progress_every = limits.progress_every;
  S.next_progress = limits.progress_every;
  S.progress = progress;
  S.current_limit = 0;
  S.fsm.init(spec);

  PieceState d;
  for (size_t i = 0; i < goals.size(); i++) {
    deriver.derive(goals[i], d);
    std::string k; state_key(d, k);
    S.goal_keys.push_back(k);
  }

  SearchOutcome result = SEARCH_NO_SOLUTION;
  long prev_level_nodes = 0, last_level_nodes = 0;

  for (int limit = 0; limit <= limits.max_depth; limit++) {
    // One record per level, filled in as the level goes and handed over when it
    // ends -- including when it ends by running out of budget, which is the
    // level that costs the most and would otherwise be the one never reported.
    DepthStat stat;
    stat.limit = limit;
    const double t_level = kc_now();

    // A table loaded from a file is skipped entirely -- neither resized nor
    // deepened. It is already what build_phase_tables.R built, and the sizing
    // and filling below are for a table the search owns and grows as it goes.
    // See PruneTable::loaded.
    if (mutable_prune && !mutable_prune->loaded) {
      // Size the table for the level about to be searched, from how the last
      // two levels actually grew: the branching factor is latest/previous, so
      // the next level is about latest * latest / previous. A table sized by a
      // constant is either wasted on the shallow levels or hopeless on the
      // deep ones, and phase 3 of a 4x4x4 is where that stops being academic.
      double want = 0.0;
      if (prev_level_nodes > 0) {
        want = (double)last_level_nodes *
               (double)last_level_nodes / (double)prev_level_nodes;
      }

      // That estimate is about the *search*: how many nodes the next level
      // will visit. The table is about the *fill*: how many entries the depth
      // it is filled to will produce. Those are different numbers, and sizing
      // by the first alone leaves the table too small for the second.
      //
      // Measured on phase 3, filling to depth 6 (bench_phase3_width.R). The
      // fill wants 8.3M entries; the search estimate stopped the width at 2^21
      // = 2M slots, a quarter of what was needed, with the phase's own 2^28
      // ceiling never touched. Widening it, with the depth held fixed:
      //
      //     2^21  25.0% full  mean bound 4.97  0 of 3 solved  200,001 nodes
      //     2^23  24.6% full  mean bound 5.59  0 of 3 solved  200,001 nodes
      //     2^25  16.3% full  mean bound 6.19  2 of 3 solved  130,324 nodes
      //     2^28   3.1% full  mean bound 6.84  2 of 3 solved   76,725 nodes
      //
      // The bound rises as the collisions thin out, because a bound is only
      // this state's own distance when nothing else claimed its slot. Filling
      // costs 76 seconds at every width, so the width is nearly free -- what it
      // costs is memory, and 2^28 is 256MB.
      //
      // So take the larger of the two demands. The fill's is read off what the
      // last fill actually wrote: levels grow by the branching factor, so the
      // next one wants about that many times the entries, and a hash table
      // wants room above its occupancy or it collides on the way in. The
      // factor of four is that headroom -- at 25% occupancy three slots in
      // four are free, which is where the measured bounds stopped being other
      // states' entries.
      if (mutable_prune->n_writes > 0) {
        const double want_fill = (double)mutable_prune->n_writes *
                                 (double)spec.n_moves() * 4.0;
        if (want_fill > want) want = want_fill;
      }
      if (want > 0.0) {
        mutable_prune->grow_to((want > 1e9) ? (size_t)1e9 : (size_t)want);
      }
      // Then fill it to half the depth about to be searched. Half is the trade
      // worth making: building one more level costs about what searching one
      // more level costs, so a table as deep as the search would cost as much
      // as the search it saves, and a much shallower one stops pruning.
      //
      // One consequence is worth knowing before reading a node count. Rounding
      // down pairs the levels: limits 2k and 2k+1 both fill the table to depth
      // k, so the odd level searches deeper against no better heuristic and its
      // node count jumps by the branching factor, while the even one that
      // follows barely moves. Phase 3 of a 4x4x4 shows it plainly -- 4955,
      // 4955, 75203, 77051 -- and it reads like alternate levels doing no work.
      //
      // They are doing work. Measured on that phase, breadth-first from the
      // goal finds new states at every depth without exception (1, 6, 83, 938,
      // 11044, 131150, 1555236), so no level is empty and skipping the ones
      // that look idle would throw away levels that hold solutions. The pattern
      // is in the table's depth, not in the puzzle's reachable depths.
      // Normally half the search depth. `prune_depth_bonus` adds to that, and
      // exists to measure what a deeper table buys: at a branching factor of
      // eleven a table one level deeper should cut the cost of a level by
      // about that factor, and whether it actually does is a question for a
      // measurement rather than an argument.
      int fill_to = limit / 2 + limits.prune_depth_bonus;
      if (fill_to > limit) fill_to = limit;
      stat.fill_to = fill_to;
      extend_prune_table(spec, deriver, goals, fill_to, *mutable_prune);
    }
    stat.fill_secs = kc_now() - t_level;

    const long nodes_before = S.nodes;
    S.current_limit = limit;
    word.clear();
    const double t_search = kc_now();
    const bool found = S.recurse(start, 0, limit, S.fsm.start(), word);

    // Closed on every exit from the level, not just the ordinary one. The two
    // interesting levels are the one that found the solution and the one that
    // spent the budget, and both leave by a `break` below.
    stat.search_secs = kc_now() - t_search;
    stat.nodes = S.nodes - nodes_before;
    if (depth_stats) depth_stats->push_back(stat);
    if (depth_done) depth_done(stat);

    if (found) { result = SEARCH_FOUND; break; }
    if (S.exhausted) { result = SEARCH_EXHAUSTED; break; }
    prev_level_nodes = last_level_nodes;
    last_level_nodes = stat.nodes;
  }
  if (nodes_used) *nodes_used = S.nodes;
  if (best_word) *best_word = S.best_word;
  if (best_bound) *best_bound = (S.best_bound == INT_MAX) ? -1 : S.best_bound;
  if (prune_stats) {
    prune_stats->lookups = S.prune_lookups;
    prune_stats->cuts = S.prune_cuts;
    prune_stats->class_cuts = S.prune_class_cuts;
    prune_stats->mean_bound = S.prune_lookups
      ? S.prune_bound_sum / (double)S.prune_lookups : 0.0;
  }
  return result;
}

// The same, for callers that only want to know whether it worked.
inline bool ida_search(const PuzzleSpec& spec, const Deriver& deriver,
                       const PruneTable& prune,
                       const std::vector<PieceState>& goals,
                       const PieceState& start, const SearchLimits& limits,
                       std::vector<int>& word) {
  return ida_search_outcome(spec, deriver, prune, goals, start, limits, word)
         == SEARCH_FOUND;
}

}  // namespace kociemba

#endif  // CAYLEYR_KOCIEMBA_CORE_H
