// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// shift_left_simple
IntegerVector shift_left_simple(IntegerVector state);
RcppExport SEXP _cayleyR_shift_left_simple(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(shift_left_simple(state));
    return rcpp_result_gen;
END_RCPP
}
// shift_right_simple
IntegerVector shift_right_simple(IntegerVector state);
RcppExport SEXP _cayleyR_shift_right_simple(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(shift_right_simple(state));
    return rcpp_result_gen;
END_RCPP
}
// reverse_prefix_simple
IntegerVector reverse_prefix_simple(IntegerVector state, int k);
RcppExport SEXP _cayleyR_reverse_prefix_simple(SEXP stateSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(reverse_prefix_simple(state, k));
    return rcpp_result_gen;
END_RCPP
}
// shift_left
List shift_left(IntegerVector state, Nullable<List> coords);
RcppExport SEXP _cayleyR_shift_left(SEXP stateSEXP, SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(shift_left(state, coords));
    return rcpp_result_gen;
END_RCPP
}
// shift_right
List shift_right(IntegerVector state, Nullable<List> coords);
RcppExport SEXP _cayleyR_shift_right(SEXP stateSEXP, SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(shift_right(state, coords));
    return rcpp_result_gen;
END_RCPP
}
// reverse_prefix
List reverse_prefix(IntegerVector state, int k, Nullable<List> coords);
RcppExport SEXP _cayleyR_reverse_prefix(SEXP stateSEXP, SEXP kSEXP, SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(reverse_prefix(state, k, coords));
    return rcpp_result_gen;
END_RCPP
}
// get_reachable_states_light_cpp
List get_reachable_states_light_cpp(IntegerVector start_state, IntegerVector allowed_positions, SEXP group, int max_moves);
RcppExport SEXP _cayleyR_get_reachable_states_light_cpp(SEXP start_stateSEXP, SEXP allowed_positionsSEXP, SEXP groupSEXP, SEXP max_movesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type start_state(start_stateSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type allowed_positions(allowed_positionsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type max_moves(max_movesSEXP);
    rcpp_result_gen = Rcpp::wrap(get_reachable_states_light_cpp(start_state, allowed_positions, group, max_moves));
    return rcpp_result_gen;
END_RCPP
}
// find_best_random_combinations_cpp
List find_best_random_combinations_cpp(IntegerVector start_state, SEXP group, IntegerVector moves, int combo_length, int n_samples, int max_moves);
RcppExport SEXP _cayleyR_find_best_random_combinations_cpp(SEXP start_stateSEXP, SEXP groupSEXP, SEXP movesSEXP, SEXP combo_lengthSEXP, SEXP n_samplesSEXP, SEXP max_movesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type start_state(start_stateSEXP);
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type moves(movesSEXP);
    Rcpp::traits::input_parameter< int >::type combo_length(combo_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type max_moves(max_movesSEXP);
    rcpp_result_gen = Rcpp::wrap(find_best_random_combinations_cpp(start_state, group, moves, combo_length, n_samples, max_moves));
    return rcpp_result_gen;
END_RCPP
}
// openmp_threads
int openmp_threads();
RcppExport SEXP _cayleyR_openmp_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(openmp_threads());
    return rcpp_result_gen;
END_RCPP
}
// apply_operations
List apply_operations(IntegerVector state, CharacterVector operations, int k, Nullable<List> coords, bool compute_coords);
RcppExport SEXP _cayleyR_apply_operations(SEXP stateSEXP, SEXP operationsSEXP, SEXP kSEXP, SEXP coordsSEXP, SEXP compute_coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type operations(operationsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_coords(compute_coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_operations(state, operations, k, coords, compute_coords));
    return rcpp_result_gen;
END_RCPP
}
// cube_adi_scramble
List cube_adi_scramble(SEXP group, int n, int max_depth);
RcppExport SEXP _cayleyR_cube_adi_scramble(SEXP groupSEXP, SEXP nSEXP, SEXP max_depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_adi_scramble(group, n, max_depth));
    return rcpp_result_gen;
END_RCPP
}
// cube_adi_children
List cube_adi_children(SEXP group, IntegerMatrix states);
RcppExport SEXP _cayleyR_cube_adi_children(SEXP groupSEXP, SEXP statesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type states(statesSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_adi_children(group, states));
    return rcpp_result_gen;
END_RCPP
}
// cube_adi_targets
List cube_adi_targets(NumericVector child_values, LogicalVector child_solved, int n_moves);
RcppExport SEXP _cayleyR_cube_adi_targets(SEXP child_valuesSEXP, SEXP child_solvedSEXP, SEXP n_movesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type child_values(child_valuesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type child_solved(child_solvedSEXP);
    Rcpp::traits::input_parameter< int >::type n_moves(n_movesSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_adi_targets(child_values, child_solved, n_moves));
    return rcpp_result_gen;
END_RCPP
}
// cube_centres_shoot_cpp
List cube_centres_shoot_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_centres_shoot_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_centres_shoot_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_centre_counts_cpp
IntegerVector cube_centre_counts_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_centre_counts_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_centre_counts_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_choose_shot_cpp
int cube_choose_shot_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_choose_shot_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_choose_shot_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_find_colour_cpp
DataFrame cube_find_colour_cpp(IntegerVector state, int colour);
RcppExport SEXP _cayleyR_cube_find_colour_cpp(SEXP stateSEXP, SEXP colourSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type colour(colourSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_find_colour_cpp(state, colour));
    return rcpp_result_gen;
END_RCPP
}
// cube_has_pair_cpp
LogicalVector cube_has_pair_cpp(IntegerVector state, int colour);
RcppExport SEXP _cayleyR_cube_has_pair_cpp(SEXP stateSEXP, SEXP colourSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type colour(colourSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_has_pair_cpp(state, colour));
    return rcpp_result_gen;
END_RCPP
}
// cube_slice_map_cpp
DataFrame cube_slice_map_cpp();
RcppExport SEXP _cayleyR_cube_slice_map_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cube_slice_map_cpp());
    return rcpp_result_gen;
END_RCPP
}
// cube_first_centre_cpp
List cube_first_centre_cpp(IntegerVector state, int target_face);
RcppExport SEXP _cayleyR_cube_first_centre_cpp(SEXP stateSEXP, SEXP target_faceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type target_face(target_faceSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_first_centre_cpp(state, target_face));
    return rcpp_result_gen;
END_RCPP
}
// cube_l_slice_count_cpp
int cube_l_slice_count_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_l_slice_count_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_l_slice_count_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_centres_12_cpp
List cube_centres_12_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_centres_12_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_centres_12_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_centres_cpp
List cube_centres_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_centres_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_centres_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_reduce_cpp
List cube_reduce_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_reduce_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_reduce_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_parity_fix_cpp
List cube_parity_fix_cpp(IntegerVector state, std::string which);
RcppExport SEXP _cayleyR_cube_parity_fix_cpp(SEXP stateSEXP, SEXP whichSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< std::string >::type which(whichSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_parity_fix_cpp(state, which));
    return rcpp_result_gen;
END_RCPP
}
// cube_squeeze_cpp
IntegerVector cube_squeeze_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_squeeze_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_squeeze_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_lift_path_cpp
List cube_lift_path_cpp(CharacterVector path);
RcppExport SEXP _cayleyR_cube_lift_path_cpp(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_lift_path_cpp(path));
    return rcpp_result_gen;
END_RCPP
}
// cube_apply_word_cpp
IntegerVector cube_apply_word_cpp(IntegerVector state, std::string word);
RcppExport SEXP _cayleyR_cube_apply_word_cpp(SEXP stateSEXP, SEXP wordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< std::string >::type word(wordSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_apply_word_cpp(state, word));
    return rcpp_result_gen;
END_RCPP
}
// cube_word_order_cpp
int cube_word_order_cpp(std::string word, int max_order);
RcppExport SEXP _cayleyR_cube_word_order_cpp(SEXP wordSEXP, SEXP max_orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type word(wordSEXP);
    Rcpp::traits::input_parameter< int >::type max_order(max_orderSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_word_order_cpp(word, max_order));
    return rcpp_result_gen;
END_RCPP
}
// cube_read_state_cpp
List cube_read_state_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_read_state_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_read_state_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_predicates_cpp
LogicalVector cube_predicates_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_predicates_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_predicates_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_alg_table_cpp
DataFrame cube_alg_table_cpp(std::string which);
RcppExport SEXP _cayleyR_cube_alg_table_cpp(SEXP whichSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type which(whichSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_alg_table_cpp(which));
    return rcpp_result_gen;
END_RCPP
}
// cube_expand_alg_cpp
CharacterVector cube_expand_alg_cpp(std::string notation);
RcppExport SEXP _cayleyR_cube_expand_alg_cpp(SEXP notationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type notation(notationSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_expand_alg_cpp(notation));
    return rcpp_result_gen;
END_RCPP
}
// cube_centre_positions_cpp
IntegerVector cube_centre_positions_cpp();
RcppExport SEXP _cayleyR_cube_centre_positions_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cube_centre_positions_cpp());
    return rcpp_result_gen;
END_RCPP
}
// cube_moves_cpp
List cube_moves_cpp(int n);
RcppExport SEXP _cayleyR_cube_moves_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_moves_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// cube_move_names_cpp
CharacterVector cube_move_names_cpp(int n);
RcppExport SEXP _cayleyR_cube_move_names_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_move_names_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// cube_layer_move_cpp
IntegerVector cube_layer_move_cpp(int n, int axis, int layer, int turns);
RcppExport SEXP _cayleyR_cube_layer_move_cpp(SEXP nSEXP, SEXP axisSEXP, SEXP layerSEXP, SEXP turnsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type axis(axisSEXP);
    Rcpp::traits::input_parameter< int >::type layer(layerSEXP);
    Rcpp::traits::input_parameter< int >::type turns(turnsSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_layer_move_cpp(n, axis, layer, turns));
    return rcpp_result_gen;
END_RCPP
}
// cube_identity_cpp
IntegerVector cube_identity_cpp(int n);
RcppExport SEXP _cayleyR_cube_identity_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_identity_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// cube_is_colour_solved_cpp
bool cube_is_colour_solved_cpp(IntegerVector state, int n);
RcppExport SEXP _cayleyR_cube_is_colour_solved_cpp(SEXP stateSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_is_colour_solved_cpp(state, n));
    return rcpp_result_gen;
END_RCPP
}
// cube_orbits_cpp
DataFrame cube_orbits_cpp(int n);
RcppExport SEXP _cayleyR_cube_orbits_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_orbits_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// cube_pieces_cpp
DataFrame cube_pieces_cpp(int n);
RcppExport SEXP _cayleyR_cube_pieces_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_pieces_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// cube_progress_cpp
DataFrame cube_progress_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_progress_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_progress_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_pieces_home_cpp
IntegerVector cube_pieces_home_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_pieces_home_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_pieces_home_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_solve_cfop_cpp
List cube_solve_cfop_cpp(IntegerVector state, int cross_depth, int slot_depth);
RcppExport SEXP _cayleyR_cube_solve_cfop_cpp(SEXP stateSEXP, SEXP cross_depthSEXP, SEXP slot_depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type cross_depth(cross_depthSEXP);
    Rcpp::traits::input_parameter< int >::type slot_depth(slot_depthSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_solve_cfop_cpp(state, cross_depth, slot_depth));
    return rcpp_result_gen;
END_RCPP
}
// cube_solve_lbl_cpp
List cube_solve_lbl_cpp(IntegerVector state, int cross_depth, int corner_depth, int edge_depth);
RcppExport SEXP _cayleyR_cube_solve_lbl_cpp(SEXP stateSEXP, SEXP cross_depthSEXP, SEXP corner_depthSEXP, SEXP edge_depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type cross_depth(cross_depthSEXP);
    Rcpp::traits::input_parameter< int >::type corner_depth(corner_depthSEXP);
    Rcpp::traits::input_parameter< int >::type edge_depth(edge_depthSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_solve_lbl_cpp(state, cross_depth, corner_depth, edge_depth));
    return rcpp_result_gen;
END_RCPP
}
// cube_solve_old_pochmann_cpp
List cube_solve_old_pochmann_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_solve_old_pochmann_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_solve_old_pochmann_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_solve_m2_cpp
List cube_solve_m2_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_solve_m2_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_solve_m2_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cycle_shortcut_cpp
List cycle_shortcut_cpp(IntegerVector start_state, IntegerVector path, SEXP group, IntegerVector points, IntegerVector moves, int combo_length, int n_samples, int n_top, IntegerVector sort_by, int max_cycle_len, int n_threads, bool verbose);
RcppExport SEXP _cayleyR_cycle_shortcut_cpp(SEXP start_stateSEXP, SEXP pathSEXP, SEXP groupSEXP, SEXP pointsSEXP, SEXP movesSEXP, SEXP combo_lengthSEXP, SEXP n_samplesSEXP, SEXP n_topSEXP, SEXP sort_bySEXP, SEXP max_cycle_lenSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type start_state(start_stateSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type path(pathSEXP);
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type moves(movesSEXP);
    Rcpp::traits::input_parameter< int >::type combo_length(combo_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type n_top(n_topSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sort_by(sort_bySEXP);
    Rcpp::traits::input_parameter< int >::type max_cycle_len(max_cycle_lenSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cycle_shortcut_cpp(start_state, path, group, points, moves, combo_length, n_samples, n_top, sort_by, max_cycle_len, n_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cayley_bfs_full_cpp
DataFrame cayley_bfs_full_cpp(IntegerVector start_state, SEXP group, IntegerVector moves);
RcppExport SEXP _cayleyR_cayley_bfs_full_cpp(SEXP start_stateSEXP, SEXP groupSEXP, SEXP movesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type start_state(start_stateSEXP);
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type moves(movesSEXP);
    rcpp_result_gen = Rcpp::wrap(cayley_bfs_full_cpp(start_state, group, moves));
    return rcpp_result_gen;
END_RCPP
}
// cayley_graph_diameter_cpp
List cayley_graph_diameter_cpp(IntegerVector start_state, SEXP group, IntegerVector moves, int method, double max_pairs, bool verbose);
RcppExport SEXP _cayleyR_cayley_graph_diameter_cpp(SEXP start_stateSEXP, SEXP groupSEXP, SEXP movesSEXP, SEXP methodSEXP, SEXP max_pairsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type start_state(start_stateSEXP);
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type moves(movesSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type max_pairs(max_pairsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cayley_graph_diameter_cpp(start_state, group, moves, method, max_pairs, verbose));
    return rcpp_result_gen;
END_RCPP
}
// human_table_probe_cpp
List human_table_probe_cpp(int n, int k);
RcppExport SEXP _cayleyR_human_table_probe_cpp(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(human_table_probe_cpp(n, k));
    return rcpp_result_gen;
END_RCPP
}
// run_length_cpp
int run_length_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_run_length_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(run_length_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// human_phase1_rank_cpp
DataFrame human_phase1_rank_cpp(IntegerVector state, int k);
RcppExport SEXP _cayleyR_human_phase1_rank_cpp(SEXP stateSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(human_phase1_rank_cpp(state, k));
    return rcpp_result_gen;
END_RCPP
}
// human_algorithm_cpp
List human_algorithm_cpp(IntegerVector start_state, int k, double max_ops, bool final_rotate);
RcppExport SEXP _cayleyR_human_algorithm_cpp(SEXP start_stateSEXP, SEXP kSEXP, SEXP max_opsSEXP, SEXP final_rotateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type start_state(start_stateSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type max_ops(max_opsSEXP);
    Rcpp::traits::input_parameter< bool >::type final_rotate(final_rotateSEXP);
    rcpp_result_gen = Rcpp::wrap(human_algorithm_cpp(start_state, k, max_ops, final_rotate));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba_cpp
CharacterVector cube_kociemba_cpp(IntegerVector state, int max_depth1, int max_depth2, double node_budget);
RcppExport SEXP _cayleyR_cube_kociemba_cpp(SEXP stateSEXP, SEXP max_depth1SEXP, SEXP max_depth2SEXP, SEXP node_budgetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth1(max_depth1SEXP);
    Rcpp::traits::input_parameter< int >::type max_depth2(max_depth2SEXP);
    Rcpp::traits::input_parameter< double >::type node_budget(node_budgetSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_kociemba_cpp(state, max_depth1, max_depth2, node_budget));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba_init_cpp
void cube_kociemba_init_cpp(double table1, int depth1, double table2, int depth2);
RcppExport SEXP _cayleyR_cube_kociemba_init_cpp(SEXP table1SEXP, SEXP depth1SEXP, SEXP table2SEXP, SEXP depth2SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type table1(table1SEXP);
    Rcpp::traits::input_parameter< int >::type depth1(depth1SEXP);
    Rcpp::traits::input_parameter< double >::type table2(table2SEXP);
    Rcpp::traits::input_parameter< int >::type depth2(depth2SEXP);
    cube_kociemba_init_cpp(table1, depth1, table2, depth2);
    return R_NilValue;
END_RCPP
}
// cube_cubie_pieces_cpp
List cube_cubie_pieces_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_cubie_pieces_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_cubie_pieces_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_in_g1_cpp
bool cube_in_g1_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_in_g1_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_in_g1_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba_last_cpp
List cube_kociemba_last_cpp();
RcppExport SEXP _cayleyR_cube_kociemba_last_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cube_kociemba_last_cpp());
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba4_reduce_cpp
CharacterVector cube_kociemba4_reduce_cpp(IntegerVector state, int max_depth1, int max_depth2, int max_depth3, double node_budget, double progress_every, int prune_depth_bonus);
RcppExport SEXP _cayleyR_cube_kociemba4_reduce_cpp(SEXP stateSEXP, SEXP max_depth1SEXP, SEXP max_depth2SEXP, SEXP max_depth3SEXP, SEXP node_budgetSEXP, SEXP progress_everySEXP, SEXP prune_depth_bonusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth1(max_depth1SEXP);
    Rcpp::traits::input_parameter< int >::type max_depth2(max_depth2SEXP);
    Rcpp::traits::input_parameter< int >::type max_depth3(max_depth3SEXP);
    Rcpp::traits::input_parameter< double >::type node_budget(node_budgetSEXP);
    Rcpp::traits::input_parameter< double >::type progress_every(progress_everySEXP);
    Rcpp::traits::input_parameter< int >::type prune_depth_bonus(prune_depth_bonusSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_kociemba4_reduce_cpp(state, max_depth1, max_depth2, max_depth3, node_budget, progress_every, prune_depth_bonus));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba4_last_cpp
List cube_kociemba4_last_cpp();
RcppExport SEXP _cayleyR_cube_kociemba4_last_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cube_kociemba4_last_cpp());
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba4_tables_cpp
List cube_kociemba4_tables_cpp();
RcppExport SEXP _cayleyR_cube_kociemba4_tables_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cube_kociemba4_tables_cpp());
    return rcpp_result_gen;
END_RCPP
}
// cube_at_phase_goal_cpp
bool cube_at_phase_goal_cpp(IntegerVector state, int phase);
RcppExport SEXP _cayleyR_cube_at_phase_goal_cpp(SEXP stateSEXP, SEXP phaseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type phase(phaseSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_at_phase_goal_cpp(state, phase));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba4_set_table_size_cpp
double cube_kociemba4_set_table_size_cpp(double slots);
RcppExport SEXP _cayleyR_cube_kociemba4_set_table_size_cpp(SEXP slotsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type slots(slotsSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_kociemba4_set_table_size_cpp(slots));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba4_save_phase3_cpp
bool cube_kociemba4_save_phase3_cpp(std::string path);
RcppExport SEXP _cayleyR_cube_kociemba4_save_phase3_cpp(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_kociemba4_save_phase3_cpp(path));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba4_load_phase3_cpp
List cube_kociemba4_load_phase3_cpp(std::string path);
RcppExport SEXP _cayleyR_cube_kociemba4_load_phase3_cpp(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_kociemba4_load_phase3_cpp(path));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba4_save_phase_cpp
bool cube_kociemba4_save_phase_cpp(std::string path, int phase);
RcppExport SEXP _cayleyR_cube_kociemba4_save_phase_cpp(SEXP pathSEXP, SEXP phaseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< int >::type phase(phaseSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_kociemba4_save_phase_cpp(path, phase));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba4_load_phase_cpp
List cube_kociemba4_load_phase_cpp(std::string path, int phase);
RcppExport SEXP _cayleyR_cube_kociemba4_load_phase_cpp(SEXP pathSEXP, SEXP phaseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< int >::type phase(phaseSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_kociemba4_load_phase_cpp(path, phase));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba4_fill_phase_cpp
List cube_kociemba4_fill_phase_cpp(int depth, int phase, double table_size, bool breadth_first, double max_frontier);
RcppExport SEXP _cayleyR_cube_kociemba4_fill_phase_cpp(SEXP depthSEXP, SEXP phaseSEXP, SEXP table_sizeSEXP, SEXP breadth_firstSEXP, SEXP max_frontierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type phase(phaseSEXP);
    Rcpp::traits::input_parameter< double >::type table_size(table_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type breadth_first(breadth_firstSEXP);
    Rcpp::traits::input_parameter< double >::type max_frontier(max_frontierSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_kociemba4_fill_phase_cpp(depth, phase, table_size, breadth_first, max_frontier));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba4_fill_phase3_cpp
List cube_kociemba4_fill_phase3_cpp(int depth, double table_size, bool breadth_first, double max_frontier);
RcppExport SEXP _cayleyR_cube_kociemba4_fill_phase3_cpp(SEXP depthSEXP, SEXP table_sizeSEXP, SEXP breadth_firstSEXP, SEXP max_frontierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< double >::type table_size(table_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type breadth_first(breadth_firstSEXP);
    Rcpp::traits::input_parameter< double >::type max_frontier(max_frontierSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_kociemba4_fill_phase3_cpp(depth, table_size, breadth_first, max_frontier));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba4_phase3_cpp
List cube_kociemba4_phase3_cpp(IntegerVector state, int max_depth3, double node_budget, int prune_depth_bonus, bool use_exact_centres, double progress_every);
RcppExport SEXP _cayleyR_cube_kociemba4_phase3_cpp(SEXP stateSEXP, SEXP max_depth3SEXP, SEXP node_budgetSEXP, SEXP prune_depth_bonusSEXP, SEXP use_exact_centresSEXP, SEXP progress_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth3(max_depth3SEXP);
    Rcpp::traits::input_parameter< double >::type node_budget(node_budgetSEXP);
    Rcpp::traits::input_parameter< int >::type prune_depth_bonus(prune_depth_bonusSEXP);
    Rcpp::traits::input_parameter< bool >::type use_exact_centres(use_exact_centresSEXP);
    Rcpp::traits::input_parameter< double >::type progress_every(progress_everySEXP);
    rcpp_result_gen = Rcpp::wrap(cube_kociemba4_phase3_cpp(state, max_depth3, node_budget, prune_depth_bonus, use_exact_centres, progress_every));
    return rcpp_result_gen;
END_RCPP
}
// cube_phase_generators_cpp
List cube_phase_generators_cpp(int phase);
RcppExport SEXP _cayleyR_cube_phase_generators_cpp(SEXP phaseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type phase(phaseSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_phase_generators_cpp(phase));
    return rcpp_result_gen;
END_RCPP
}
// cube_to_pieces4_cpp
List cube_to_pieces4_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_to_pieces4_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_to_pieces4_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_phase3_coord_cpp
List cube_phase3_coord_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_phase3_coord_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_phase3_coord_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_wing_parities_cpp
List cube_wing_parities_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_wing_parities_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_wing_parities_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_phase_goal_keys_cpp
List cube_phase_goal_keys_cpp(int phase);
RcppExport SEXP _cayleyR_cube_phase_goal_keys_cpp(SEXP phaseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type phase(phaseSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_phase_goal_keys_cpp(phase));
    return rcpp_result_gen;
END_RCPP
}
// cube_is_reduced_cpp
bool cube_is_reduced_cpp(IntegerVector state);
RcppExport SEXP _cayleyR_cube_is_reduced_cpp(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_is_reduced_cpp(state));
    return rcpp_result_gen;
END_RCPP
}
// cube_fsm_size_cpp
List cube_fsm_size_cpp(int n);
RcppExport SEXP _cayleyR_cube_fsm_size_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_fsm_size_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba4_phase12_cpp
CharacterVector cube_kociemba4_phase12_cpp(IntegerVector state, int upto_phase, int max_depth1, int max_depth2, double node_budget);
RcppExport SEXP _cayleyR_cube_kociemba4_phase12_cpp(SEXP stateSEXP, SEXP upto_phaseSEXP, SEXP max_depth1SEXP, SEXP max_depth2SEXP, SEXP node_budgetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type upto_phase(upto_phaseSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth1(max_depth1SEXP);
    Rcpp::traits::input_parameter< int >::type max_depth2(max_depth2SEXP);
    Rcpp::traits::input_parameter< double >::type node_budget(node_budgetSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_kociemba4_phase12_cpp(state, upto_phase, max_depth1, max_depth2, node_budget));
    return rcpp_result_gen;
END_RCPP
}
// cube_kociemba4_phase2_solutions_cpp
List cube_kociemba4_phase2_solutions_cpp(IntegerVector state, int n_solutions, int max_depth1, int max_depth2, double node_budget);
RcppExport SEXP _cayleyR_cube_kociemba4_phase2_solutions_cpp(SEXP stateSEXP, SEXP n_solutionsSEXP, SEXP max_depth1SEXP, SEXP max_depth2SEXP, SEXP node_budgetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type n_solutions(n_solutionsSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth1(max_depth1SEXP);
    Rcpp::traits::input_parameter< int >::type max_depth2(max_depth2SEXP);
    Rcpp::traits::input_parameter< double >::type node_budget(node_budgetSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_kociemba4_phase2_solutions_cpp(state, n_solutions, max_depth1, max_depth2, node_budget));
    return rcpp_result_gen;
END_RCPP
}
// cube_wing_geometry_cpp
List cube_wing_geometry_cpp();
RcppExport SEXP _cayleyR_cube_wing_geometry_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cube_wing_geometry_cpp());
    return rcpp_result_gen;
END_RCPP
}
// perm_group_create_table_cpp
SEXP perm_group_create_table_cpp(int state_length, CharacterVector move_names, List move_perms);
RcppExport SEXP _cayleyR_perm_group_create_table_cpp(SEXP state_lengthSEXP, SEXP move_namesSEXP, SEXP move_permsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type state_length(state_lengthSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type move_names(move_namesSEXP);
    Rcpp::traits::input_parameter< List >::type move_perms(move_permsSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_group_create_table_cpp(state_length, move_names, move_perms));
    return rcpp_result_gen;
END_RCPP
}
// perm_group_create_topspin_cpp
SEXP perm_group_create_topspin_cpp(int state_length, int k, CharacterVector move_names);
RcppExport SEXP _cayleyR_perm_group_create_topspin_cpp(SEXP state_lengthSEXP, SEXP kSEXP, SEXP move_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type state_length(state_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type move_names(move_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_group_create_topspin_cpp(state_length, k, move_names));
    return rcpp_result_gen;
END_RCPP
}
// perm_group_info_cpp
List perm_group_info_cpp(SEXP group);
RcppExport SEXP _cayleyR_perm_group_info_cpp(SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_group_info_cpp(group));
    return rcpp_result_gen;
END_RCPP
}
// perm_group_apply_cpp
IntegerVector perm_group_apply_cpp(SEXP group, IntegerVector state, IntegerVector word);
RcppExport SEXP _cayleyR_perm_group_apply_cpp(SEXP groupSEXP, SEXP stateSEXP, SEXP wordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type word(wordSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_group_apply_cpp(group, state, word));
    return rcpp_result_gen;
END_RCPP
}
// perm_group_compose_cpp
IntegerVector perm_group_compose_cpp(SEXP group, IntegerVector word);
RcppExport SEXP _cayleyR_perm_group_compose_cpp(SEXP groupSEXP, SEXP wordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type word(wordSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_group_compose_cpp(group, word));
    return rcpp_result_gen;
END_RCPP
}
// perm_group_inverse_seq_cpp
IntegerVector perm_group_inverse_seq_cpp(SEXP group, IntegerVector word);
RcppExport SEXP _cayleyR_perm_group_inverse_seq_cpp(SEXP groupSEXP, SEXP wordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type word(wordSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_group_inverse_seq_cpp(group, word));
    return rcpp_result_gen;
END_RCPP
}
// perm_group_identity_cpp
IntegerVector perm_group_identity_cpp(SEXP group);
RcppExport SEXP _cayleyR_perm_group_identity_cpp(SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_group_identity_cpp(group));
    return rcpp_result_gen;
END_RCPP
}
// short_path_bfs_cpp
List short_path_bfs_cpp(IntegerVector start_state, IntegerVector path, SEXP group, IntegerVector moves, int depth);
RcppExport SEXP _cayleyR_short_path_bfs_cpp(SEXP start_stateSEXP, SEXP pathSEXP, SEXP groupSEXP, SEXP movesSEXP, SEXP depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type start_state(start_stateSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type path(pathSEXP);
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type moves(movesSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    rcpp_result_gen = Rcpp::wrap(short_path_bfs_cpp(start_state, path, group, moves, depth));
    return rcpp_result_gen;
END_RCPP
}
// sparse_bfs_cpp
DataFrame sparse_bfs_cpp(IntegerVector start_state, SEXP group, IntegerVector moves, int n_hubs, int n_random, int max_levels);
RcppExport SEXP _cayleyR_sparse_bfs_cpp(SEXP start_stateSEXP, SEXP groupSEXP, SEXP movesSEXP, SEXP n_hubsSEXP, SEXP n_randomSEXP, SEXP max_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type start_state(start_stateSEXP);
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type moves(movesSEXP);
    Rcpp::traits::input_parameter< int >::type n_hubs(n_hubsSEXP);
    Rcpp::traits::input_parameter< int >::type n_random(n_randomSEXP);
    Rcpp::traits::input_parameter< int >::type max_levels(max_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_bfs_cpp(start_state, group, moves, n_hubs, n_random, max_levels));
    return rcpp_result_gen;
END_RCPP
}
// state_store_create
SEXP state_store_create(int perm_length, int init_capacity, SEXP group);
RcppExport SEXP _cayleyR_state_store_create(SEXP perm_lengthSEXP, SEXP init_capacitySEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type perm_length(perm_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type init_capacity(init_capacitySEXP);
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_create(perm_length, init_capacity, group));
    return rcpp_result_gen;
END_RCPP
}
// state_store_size
int state_store_size(SEXP xp);
RcppExport SEXP _cayleyR_state_store_size(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_size(xp));
    return rcpp_result_gen;
END_RCPP
}
// state_store_unique_count
int state_store_unique_count(SEXP xp);
RcppExport SEXP _cayleyR_state_store_unique_count(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_unique_count(xp));
    return rcpp_result_gen;
END_RCPP
}
// state_store_perm_length
int state_store_perm_length(SEXP xp);
RcppExport SEXP _cayleyR_state_store_perm_length(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_perm_length(xp));
    return rcpp_result_gen;
END_RCPP
}
// state_store_add_batch
int state_store_add_batch(SEXP xp, IntegerMatrix states_mat, IntegerVector step_vec, IntegerVector combo_vec, int cycle_val, IntegerVector op_vec, IntegerVector nL_vec, IntegerVector nR_vec, IntegerVector nX_vec, NumericVector theta_vec, NumericVector phi_vec, NumericVector omega_vec);
RcppExport SEXP _cayleyR_state_store_add_batch(SEXP xpSEXP, SEXP states_matSEXP, SEXP step_vecSEXP, SEXP combo_vecSEXP, SEXP cycle_valSEXP, SEXP op_vecSEXP, SEXP nL_vecSEXP, SEXP nR_vecSEXP, SEXP nX_vecSEXP, SEXP theta_vecSEXP, SEXP phi_vecSEXP, SEXP omega_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type states_mat(states_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type step_vec(step_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type combo_vec(combo_vecSEXP);
    Rcpp::traits::input_parameter< int >::type cycle_val(cycle_valSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type op_vec(op_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nL_vec(nL_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nR_vec(nR_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nX_vec(nX_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta_vec(theta_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi_vec(phi_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega_vec(omega_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_add_batch(xp, states_mat, step_vec, combo_vec, cycle_val, op_vec, nL_vec, nR_vec, nX_vec, theta_vec, phi_vec, omega_vec));
    return rcpp_result_gen;
END_RCPP
}
// state_store_get_state
IntegerVector state_store_get_state(SEXP xp, int idx);
RcppExport SEXP _cayleyR_state_store_get_state(SEXP xpSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< int >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_get_state(xp, idx));
    return rcpp_result_gen;
END_RCPP
}
// state_store_get_meta
List state_store_get_meta(SEXP xp, int idx);
RcppExport SEXP _cayleyR_state_store_get_meta(SEXP xpSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< int >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_get_meta(xp, idx));
    return rcpp_result_gen;
END_RCPP
}
// state_store_lookup
IntegerVector state_store_lookup(SEXP xp, std::string key);
RcppExport SEXP _cayleyR_state_store_lookup(SEXP xpSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_lookup(xp, key));
    return rcpp_result_gen;
END_RCPP
}
// state_store_lookup_state
IntegerVector state_store_lookup_state(SEXP xp, IntegerVector state);
RcppExport SEXP _cayleyR_state_store_lookup_state(SEXP xpSEXP, SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_lookup_state(xp, state));
    return rcpp_result_gen;
END_RCPP
}
// state_store_find_intersections
CharacterVector state_store_find_intersections(SEXP xp_a, SEXP xp_b);
RcppExport SEXP _cayleyR_state_store_find_intersections(SEXP xp_aSEXP, SEXP xp_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp_a(xp_aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xp_b(xp_bSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_find_intersections(xp_a, xp_b));
    return rcpp_result_gen;
END_RCPP
}
// state_store_find_best_match
int state_store_find_best_match(SEXP xp, IntegerVector target, IntegerVector candidate_indices);
RcppExport SEXP _cayleyR_state_store_find_best_match(SEXP xpSEXP, SEXP targetSEXP, SEXP candidate_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type candidate_indices(candidate_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_find_best_match(xp, target, candidate_indices));
    return rcpp_result_gen;
END_RCPP
}
// state_store_get_states
IntegerMatrix state_store_get_states(SEXP xp, IntegerVector indices);
RcppExport SEXP _cayleyR_state_store_get_states(SEXP xpSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_get_states(xp, indices));
    return rcpp_result_gen;
END_RCPP
}
// human_distance_cpp
NumericVector human_distance_cpp(IntegerMatrix states, IntegerVector target, int k);
RcppExport SEXP _cayleyR_human_distance_cpp(SEXP statesSEXP, SEXP targetSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type states(statesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(human_distance_cpp(states, target, k));
    return rcpp_result_gen;
END_RCPP
}
// state_store_human_scores
NumericVector state_store_human_scores(SEXP xp, IntegerVector candidate_indices, IntegerVector target, int k);
RcppExport SEXP _cayleyR_state_store_human_scores(SEXP xpSEXP, SEXP candidate_indicesSEXP, SEXP targetSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type candidate_indices(candidate_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_human_scores(xp, candidate_indices, target, k));
    return rcpp_result_gen;
END_RCPP
}
// state_store_find_best_match_scored
int state_store_find_best_match_scored(SEXP xp, IntegerVector candidate_indices, NumericVector scores);
RcppExport SEXP _cayleyR_state_store_find_best_match_scored(SEXP xpSEXP, SEXP candidate_indicesSEXP, SEXP scoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type candidate_indices(candidate_indicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type scores(scoresSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_find_best_match_scored(xp, candidate_indices, scores));
    return rcpp_result_gen;
END_RCPP
}
// state_store_indices_for_cycle
IntegerVector state_store_indices_for_cycle(SEXP xp, int target_cycle);
RcppExport SEXP _cayleyR_state_store_indices_for_cycle(SEXP xpSEXP, SEXP target_cycleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< int >::type target_cycle(target_cycleSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_indices_for_cycle(xp, target_cycle));
    return rcpp_result_gen;
END_RCPP
}
// state_store_filter_middle
IntegerVector state_store_filter_middle(SEXP xp, int target_cycle, int skip_first, int skip_last);
RcppExport SEXP _cayleyR_state_store_filter_middle(SEXP xpSEXP, SEXP target_cycleSEXP, SEXP skip_firstSEXP, SEXP skip_lastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< int >::type target_cycle(target_cycleSEXP);
    Rcpp::traits::input_parameter< int >::type skip_first(skip_firstSEXP);
    Rcpp::traits::input_parameter< int >::type skip_last(skip_lastSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_filter_middle(xp, target_cycle, skip_first, skip_last));
    return rcpp_result_gen;
END_RCPP
}
// state_store_set_opd
void state_store_set_opd(SEXP xp, int target_cycle, IntegerVector combos);
RcppExport SEXP _cayleyR_state_store_set_opd(SEXP xpSEXP, SEXP target_cycleSEXP, SEXP combosSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< int >::type target_cycle(target_cycleSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type combos(combosSEXP);
    state_store_set_opd(xp, target_cycle, combos);
    return R_NilValue;
END_RCPP
}
// state_store_clear_opd
void state_store_clear_opd(SEXP xp);
RcppExport SEXP _cayleyR_state_store_clear_opd(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    state_store_clear_opd(xp);
    return R_NilValue;
END_RCPP
}
// state_store_clear
void state_store_clear(SEXP xp);
RcppExport SEXP _cayleyR_state_store_clear(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    state_store_clear(xp);
    return R_NilValue;
END_RCPP
}
// state_store_combos_for_state
IntegerVector state_store_combos_for_state(SEXP xp, IntegerVector state_vec, int target_cycle);
RcppExport SEXP _cayleyR_state_store_combos_for_state(SEXP xpSEXP, SEXP state_vecSEXP, SEXP target_cycleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type state_vec(state_vecSEXP);
    Rcpp::traits::input_parameter< int >::type target_cycle(target_cycleSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_combos_for_state(xp, state_vec, target_cycle));
    return rcpp_result_gen;
END_RCPP
}
// state_store_to_dataframe
DataFrame state_store_to_dataframe(SEXP xp);
RcppExport SEXP _cayleyR_state_store_to_dataframe(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_to_dataframe(xp));
    return rcpp_result_gen;
END_RCPP
}
// state_store_collect_ops
CharacterVector state_store_collect_ops(SEXP xp, int target_cycle, int target_combo, int end_step);
RcppExport SEXP _cayleyR_state_store_collect_ops(SEXP xpSEXP, SEXP target_cycleSEXP, SEXP target_comboSEXP, SEXP end_stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< int >::type target_cycle(target_cycleSEXP);
    Rcpp::traits::input_parameter< int >::type target_combo(target_comboSEXP);
    Rcpp::traits::input_parameter< int >::type end_step(end_stepSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_collect_ops(xp, target_cycle, target_combo, end_step));
    return rcpp_result_gen;
END_RCPP
}
// state_store_reconstruct_path
Nullable<CharacterVector> state_store_reconstruct_path(SEXP xp, IntegerMatrix bridge_states_mat, IntegerVector target_state_vec, int target_cycle, int target_combo);
RcppExport SEXP _cayleyR_state_store_reconstruct_path(SEXP xpSEXP, SEXP bridge_states_matSEXP, SEXP target_state_vecSEXP, SEXP target_cycleSEXP, SEXP target_comboSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type bridge_states_mat(bridge_states_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type target_state_vec(target_state_vecSEXP);
    Rcpp::traits::input_parameter< int >::type target_cycle(target_cycleSEXP);
    Rcpp::traits::input_parameter< int >::type target_combo(target_comboSEXP);
    rcpp_result_gen = Rcpp::wrap(state_store_reconstruct_path(xp, bridge_states_mat, target_state_vec, target_cycle, target_combo));
    return rcpp_result_gen;
END_RCPP
}
// analyze_combos_to_store_cpp
int analyze_combos_to_store_cpp(SEXP xp, List combinations, IntegerVector start_state, SEXP group, int cycle_val, int max_reps);
RcppExport SEXP _cayleyR_analyze_combos_to_store_cpp(SEXP xpSEXP, SEXP combinationsSEXP, SEXP start_stateSEXP, SEXP groupSEXP, SEXP cycle_valSEXP, SEXP max_repsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< List >::type combinations(combinationsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type start_state(start_stateSEXP);
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type cycle_val(cycle_valSEXP);
    Rcpp::traits::input_parameter< int >::type max_reps(max_repsSEXP);
    rcpp_result_gen = Rcpp::wrap(analyze_combos_to_store_cpp(xp, combinations, start_state, group, cycle_val, max_reps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cayleyR_shift_left_simple", (DL_FUNC) &_cayleyR_shift_left_simple, 1},
    {"_cayleyR_shift_right_simple", (DL_FUNC) &_cayleyR_shift_right_simple, 1},
    {"_cayleyR_reverse_prefix_simple", (DL_FUNC) &_cayleyR_reverse_prefix_simple, 2},
    {"_cayleyR_shift_left", (DL_FUNC) &_cayleyR_shift_left, 2},
    {"_cayleyR_shift_right", (DL_FUNC) &_cayleyR_shift_right, 2},
    {"_cayleyR_reverse_prefix", (DL_FUNC) &_cayleyR_reverse_prefix, 3},
    {"_cayleyR_get_reachable_states_light_cpp", (DL_FUNC) &_cayleyR_get_reachable_states_light_cpp, 4},
    {"_cayleyR_find_best_random_combinations_cpp", (DL_FUNC) &_cayleyR_find_best_random_combinations_cpp, 6},
    {"_cayleyR_openmp_threads", (DL_FUNC) &_cayleyR_openmp_threads, 0},
    {"_cayleyR_apply_operations", (DL_FUNC) &_cayleyR_apply_operations, 5},
    {"_cayleyR_cube_adi_scramble", (DL_FUNC) &_cayleyR_cube_adi_scramble, 3},
    {"_cayleyR_cube_adi_children", (DL_FUNC) &_cayleyR_cube_adi_children, 2},
    {"_cayleyR_cube_adi_targets", (DL_FUNC) &_cayleyR_cube_adi_targets, 3},
    {"_cayleyR_cube_centres_shoot_cpp", (DL_FUNC) &_cayleyR_cube_centres_shoot_cpp, 1},
    {"_cayleyR_cube_centre_counts_cpp", (DL_FUNC) &_cayleyR_cube_centre_counts_cpp, 1},
    {"_cayleyR_cube_choose_shot_cpp", (DL_FUNC) &_cayleyR_cube_choose_shot_cpp, 1},
    {"_cayleyR_cube_find_colour_cpp", (DL_FUNC) &_cayleyR_cube_find_colour_cpp, 2},
    {"_cayleyR_cube_has_pair_cpp", (DL_FUNC) &_cayleyR_cube_has_pair_cpp, 2},
    {"_cayleyR_cube_slice_map_cpp", (DL_FUNC) &_cayleyR_cube_slice_map_cpp, 0},
    {"_cayleyR_cube_first_centre_cpp", (DL_FUNC) &_cayleyR_cube_first_centre_cpp, 2},
    {"_cayleyR_cube_l_slice_count_cpp", (DL_FUNC) &_cayleyR_cube_l_slice_count_cpp, 1},
    {"_cayleyR_cube_centres_12_cpp", (DL_FUNC) &_cayleyR_cube_centres_12_cpp, 1},
    {"_cayleyR_cube_centres_cpp", (DL_FUNC) &_cayleyR_cube_centres_cpp, 1},
    {"_cayleyR_cube_reduce_cpp", (DL_FUNC) &_cayleyR_cube_reduce_cpp, 1},
    {"_cayleyR_cube_parity_fix_cpp", (DL_FUNC) &_cayleyR_cube_parity_fix_cpp, 2},
    {"_cayleyR_cube_squeeze_cpp", (DL_FUNC) &_cayleyR_cube_squeeze_cpp, 1},
    {"_cayleyR_cube_lift_path_cpp", (DL_FUNC) &_cayleyR_cube_lift_path_cpp, 1},
    {"_cayleyR_cube_apply_word_cpp", (DL_FUNC) &_cayleyR_cube_apply_word_cpp, 2},
    {"_cayleyR_cube_word_order_cpp", (DL_FUNC) &_cayleyR_cube_word_order_cpp, 2},
    {"_cayleyR_cube_read_state_cpp", (DL_FUNC) &_cayleyR_cube_read_state_cpp, 1},
    {"_cayleyR_cube_predicates_cpp", (DL_FUNC) &_cayleyR_cube_predicates_cpp, 1},
    {"_cayleyR_cube_alg_table_cpp", (DL_FUNC) &_cayleyR_cube_alg_table_cpp, 1},
    {"_cayleyR_cube_expand_alg_cpp", (DL_FUNC) &_cayleyR_cube_expand_alg_cpp, 1},
    {"_cayleyR_cube_centre_positions_cpp", (DL_FUNC) &_cayleyR_cube_centre_positions_cpp, 0},
    {"_cayleyR_cube_moves_cpp", (DL_FUNC) &_cayleyR_cube_moves_cpp, 1},
    {"_cayleyR_cube_move_names_cpp", (DL_FUNC) &_cayleyR_cube_move_names_cpp, 1},
    {"_cayleyR_cube_layer_move_cpp", (DL_FUNC) &_cayleyR_cube_layer_move_cpp, 4},
    {"_cayleyR_cube_identity_cpp", (DL_FUNC) &_cayleyR_cube_identity_cpp, 1},
    {"_cayleyR_cube_is_colour_solved_cpp", (DL_FUNC) &_cayleyR_cube_is_colour_solved_cpp, 2},
    {"_cayleyR_cube_orbits_cpp", (DL_FUNC) &_cayleyR_cube_orbits_cpp, 1},
    {"_cayleyR_cube_pieces_cpp", (DL_FUNC) &_cayleyR_cube_pieces_cpp, 1},
    {"_cayleyR_cube_progress_cpp", (DL_FUNC) &_cayleyR_cube_progress_cpp, 1},
    {"_cayleyR_cube_pieces_home_cpp", (DL_FUNC) &_cayleyR_cube_pieces_home_cpp, 1},
    {"_cayleyR_cube_solve_cfop_cpp", (DL_FUNC) &_cayleyR_cube_solve_cfop_cpp, 3},
    {"_cayleyR_cube_solve_lbl_cpp", (DL_FUNC) &_cayleyR_cube_solve_lbl_cpp, 4},
    {"_cayleyR_cube_solve_old_pochmann_cpp", (DL_FUNC) &_cayleyR_cube_solve_old_pochmann_cpp, 1},
    {"_cayleyR_cube_solve_m2_cpp", (DL_FUNC) &_cayleyR_cube_solve_m2_cpp, 1},
    {"_cayleyR_cycle_shortcut_cpp", (DL_FUNC) &_cayleyR_cycle_shortcut_cpp, 12},
    {"_cayleyR_cayley_bfs_full_cpp", (DL_FUNC) &_cayleyR_cayley_bfs_full_cpp, 3},
    {"_cayleyR_cayley_graph_diameter_cpp", (DL_FUNC) &_cayleyR_cayley_graph_diameter_cpp, 6},
    {"_cayleyR_human_table_probe_cpp", (DL_FUNC) &_cayleyR_human_table_probe_cpp, 2},
    {"_cayleyR_run_length_cpp", (DL_FUNC) &_cayleyR_run_length_cpp, 1},
    {"_cayleyR_human_phase1_rank_cpp", (DL_FUNC) &_cayleyR_human_phase1_rank_cpp, 2},
    {"_cayleyR_human_algorithm_cpp", (DL_FUNC) &_cayleyR_human_algorithm_cpp, 4},
    {"_cayleyR_cube_kociemba_cpp", (DL_FUNC) &_cayleyR_cube_kociemba_cpp, 4},
    {"_cayleyR_cube_kociemba_init_cpp", (DL_FUNC) &_cayleyR_cube_kociemba_init_cpp, 4},
    {"_cayleyR_cube_cubie_pieces_cpp", (DL_FUNC) &_cayleyR_cube_cubie_pieces_cpp, 1},
    {"_cayleyR_cube_in_g1_cpp", (DL_FUNC) &_cayleyR_cube_in_g1_cpp, 1},
    {"_cayleyR_cube_kociemba_last_cpp", (DL_FUNC) &_cayleyR_cube_kociemba_last_cpp, 0},
    {"_cayleyR_cube_kociemba4_reduce_cpp", (DL_FUNC) &_cayleyR_cube_kociemba4_reduce_cpp, 7},
    {"_cayleyR_cube_kociemba4_last_cpp", (DL_FUNC) &_cayleyR_cube_kociemba4_last_cpp, 0},
    {"_cayleyR_cube_kociemba4_tables_cpp", (DL_FUNC) &_cayleyR_cube_kociemba4_tables_cpp, 0},
    {"_cayleyR_cube_at_phase_goal_cpp", (DL_FUNC) &_cayleyR_cube_at_phase_goal_cpp, 2},
    {"_cayleyR_cube_kociemba4_set_table_size_cpp", (DL_FUNC) &_cayleyR_cube_kociemba4_set_table_size_cpp, 1},
    {"_cayleyR_cube_kociemba4_save_phase3_cpp", (DL_FUNC) &_cayleyR_cube_kociemba4_save_phase3_cpp, 1},
    {"_cayleyR_cube_kociemba4_load_phase3_cpp", (DL_FUNC) &_cayleyR_cube_kociemba4_load_phase3_cpp, 1},
    {"_cayleyR_cube_kociemba4_save_phase_cpp", (DL_FUNC) &_cayleyR_cube_kociemba4_save_phase_cpp, 2},
    {"_cayleyR_cube_kociemba4_load_phase_cpp", (DL_FUNC) &_cayleyR_cube_kociemba4_load_phase_cpp, 2},
    {"_cayleyR_cube_kociemba4_fill_phase_cpp", (DL_FUNC) &_cayleyR_cube_kociemba4_fill_phase_cpp, 5},
    {"_cayleyR_cube_kociemba4_fill_phase3_cpp", (DL_FUNC) &_cayleyR_cube_kociemba4_fill_phase3_cpp, 4},
    {"_cayleyR_cube_kociemba4_phase3_cpp", (DL_FUNC) &_cayleyR_cube_kociemba4_phase3_cpp, 6},
    {"_cayleyR_cube_phase_generators_cpp", (DL_FUNC) &_cayleyR_cube_phase_generators_cpp, 1},
    {"_cayleyR_cube_to_pieces4_cpp", (DL_FUNC) &_cayleyR_cube_to_pieces4_cpp, 1},
    {"_cayleyR_cube_phase3_coord_cpp", (DL_FUNC) &_cayleyR_cube_phase3_coord_cpp, 1},
    {"_cayleyR_cube_wing_parities_cpp", (DL_FUNC) &_cayleyR_cube_wing_parities_cpp, 1},
    {"_cayleyR_cube_phase_goal_keys_cpp", (DL_FUNC) &_cayleyR_cube_phase_goal_keys_cpp, 1},
    {"_cayleyR_cube_is_reduced_cpp", (DL_FUNC) &_cayleyR_cube_is_reduced_cpp, 1},
    {"_cayleyR_cube_fsm_size_cpp", (DL_FUNC) &_cayleyR_cube_fsm_size_cpp, 1},
    {"_cayleyR_cube_kociemba4_phase12_cpp", (DL_FUNC) &_cayleyR_cube_kociemba4_phase12_cpp, 5},
    {"_cayleyR_cube_kociemba4_phase2_solutions_cpp", (DL_FUNC) &_cayleyR_cube_kociemba4_phase2_solutions_cpp, 5},
    {"_cayleyR_cube_wing_geometry_cpp", (DL_FUNC) &_cayleyR_cube_wing_geometry_cpp, 0},
    {"_cayleyR_perm_group_create_table_cpp", (DL_FUNC) &_cayleyR_perm_group_create_table_cpp, 3},
    {"_cayleyR_perm_group_create_topspin_cpp", (DL_FUNC) &_cayleyR_perm_group_create_topspin_cpp, 3},
    {"_cayleyR_perm_group_info_cpp", (DL_FUNC) &_cayleyR_perm_group_info_cpp, 1},
    {"_cayleyR_perm_group_apply_cpp", (DL_FUNC) &_cayleyR_perm_group_apply_cpp, 3},
    {"_cayleyR_perm_group_compose_cpp", (DL_FUNC) &_cayleyR_perm_group_compose_cpp, 2},
    {"_cayleyR_perm_group_inverse_seq_cpp", (DL_FUNC) &_cayleyR_perm_group_inverse_seq_cpp, 2},
    {"_cayleyR_perm_group_identity_cpp", (DL_FUNC) &_cayleyR_perm_group_identity_cpp, 1},
    {"_cayleyR_short_path_bfs_cpp", (DL_FUNC) &_cayleyR_short_path_bfs_cpp, 5},
    {"_cayleyR_sparse_bfs_cpp", (DL_FUNC) &_cayleyR_sparse_bfs_cpp, 6},
    {"_cayleyR_state_store_create", (DL_FUNC) &_cayleyR_state_store_create, 3},
    {"_cayleyR_state_store_size", (DL_FUNC) &_cayleyR_state_store_size, 1},
    {"_cayleyR_state_store_unique_count", (DL_FUNC) &_cayleyR_state_store_unique_count, 1},
    {"_cayleyR_state_store_perm_length", (DL_FUNC) &_cayleyR_state_store_perm_length, 1},
    {"_cayleyR_state_store_add_batch", (DL_FUNC) &_cayleyR_state_store_add_batch, 12},
    {"_cayleyR_state_store_get_state", (DL_FUNC) &_cayleyR_state_store_get_state, 2},
    {"_cayleyR_state_store_get_meta", (DL_FUNC) &_cayleyR_state_store_get_meta, 2},
    {"_cayleyR_state_store_lookup", (DL_FUNC) &_cayleyR_state_store_lookup, 2},
    {"_cayleyR_state_store_lookup_state", (DL_FUNC) &_cayleyR_state_store_lookup_state, 2},
    {"_cayleyR_state_store_find_intersections", (DL_FUNC) &_cayleyR_state_store_find_intersections, 2},
    {"_cayleyR_state_store_find_best_match", (DL_FUNC) &_cayleyR_state_store_find_best_match, 3},
    {"_cayleyR_state_store_get_states", (DL_FUNC) &_cayleyR_state_store_get_states, 2},
    {"_cayleyR_human_distance_cpp", (DL_FUNC) &_cayleyR_human_distance_cpp, 3},
    {"_cayleyR_state_store_human_scores", (DL_FUNC) &_cayleyR_state_store_human_scores, 4},
    {"_cayleyR_state_store_find_best_match_scored", (DL_FUNC) &_cayleyR_state_store_find_best_match_scored, 3},
    {"_cayleyR_state_store_indices_for_cycle", (DL_FUNC) &_cayleyR_state_store_indices_for_cycle, 2},
    {"_cayleyR_state_store_filter_middle", (DL_FUNC) &_cayleyR_state_store_filter_middle, 4},
    {"_cayleyR_state_store_set_opd", (DL_FUNC) &_cayleyR_state_store_set_opd, 3},
    {"_cayleyR_state_store_clear_opd", (DL_FUNC) &_cayleyR_state_store_clear_opd, 1},
    {"_cayleyR_state_store_clear", (DL_FUNC) &_cayleyR_state_store_clear, 1},
    {"_cayleyR_state_store_combos_for_state", (DL_FUNC) &_cayleyR_state_store_combos_for_state, 3},
    {"_cayleyR_state_store_to_dataframe", (DL_FUNC) &_cayleyR_state_store_to_dataframe, 1},
    {"_cayleyR_state_store_collect_ops", (DL_FUNC) &_cayleyR_state_store_collect_ops, 4},
    {"_cayleyR_state_store_reconstruct_path", (DL_FUNC) &_cayleyR_state_store_reconstruct_path, 5},
    {"_cayleyR_analyze_combos_to_store_cpp", (DL_FUNC) &_cayleyR_analyze_combos_to_store_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_cayleyR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
